# 부도기업예측을 위한 재무변수 전처리<br>

1. 거래소번호 수 6자리 맞추기 -> 0으로 맞춰도 새로 CVS read시 0 다 누락되어 처리하지않기로 함 <br>
2. nan값 해결해야합니당 -> 결측치가 많은 칼럼은 중요도를 따진 후 feature selection 전 드랍 예정<br>
3. KIND에서 가져온 공시정보다 매칭되지 않은 13개 기업 공시제목 강제할당 처리 완 


In [232]:
del train, train_full, bankrupt, merged, df

In [233]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import plotly.express as px
import tqdm

In [234]:
train_full = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\코드_재무변수.csv', encoding='euc-kr')
train = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\코드_재무변수.csv', encoding='euc-kr', usecols = ['회사명','거래소코드','회계년도','소속코드','상장폐지일'])
bankrupt = pd.read_csv(r'C:\Users\user\Desktop\code\부실기업\kind_bankrupt_df.csv', index_col=0)

In [235]:
#회계년도 추출
# train['년'] = train['회계년도'].str[:4]
# train_full['년'] = train_full['회계년도'].str[:4]

#회계년도+1 칼럼 생성 : 사업보고서 연도와 공시 데이터 연도 시점차이로 인해 +1
train['년'] = train['회계년도'].str[0:4].astype(int) + 1
train_full['년'] = train_full['회계년도'].str[0:4].astype(int) + 1

### KIND에서 추출한 상폐관련 공시 리스트 CSV화

In [236]:
# d0002 = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\부도사유데이터\부도사유0002.csv')
# d0305 = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\부도사유데이터\부도사유0305.csv')
# d0608 = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\부도사유데이터\부도사유0608.csv')
# d0911 = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\부도사유데이터\부도사유0911.csv')
# d1214 = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\부도사유데이터\부도사유1214.csv')
# d1517 = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\부도사유데이터\부도사유1517.csv')
# d1820 = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\부도사유데이터\부도사유1820.csv')

In [237]:
# bankrupt_df = pd.concat([d0002, d0305,d0608, d0911, d1214, d1517, d1820], axis=0).reset_index()
# bankrupt_df.drop(columns=['index'], inplace=True)

In [238]:
bankrupt_df

번호                시간     회사명    종목코드  \
0     24  2002-10-31 18:27    정산애강   22220   
1     23  2002-10-08 12:06   대호특수강   21040   
2     22  2002-05-21 18:16   에이치엘비   28300   
3     21  2002-04-17 17:42   에이치엘비   28300   
4     20  2001-12-26 14:58   대호특수강   21040   
..   ...               ...     ...     ...   
389  155  2020-02-12 16:21  에스앤더블류  103230   
390  154  2020-02-11 17:02     파나진   46210   
391  153  2020-02-10 16:32     국순당   43650   
392  152  2020-02-10 16:24    유아이디   69330   
393  151  2020-02-07 17:14     이녹스   88390   

                                             공시제목     제출인  
0                                     부도발생및은행거래정지    정산애강  
1                                          은행거래재개   대호특수강  
2                                      회사정리절차종결결정   에이치엘비  
3                                      회사정리절차종결신청   에이치엘비  
4                                      회사정리절차개시결정   대호특수강  
..                                            ...     ...  
389                  내부결산시점 관리종목 지정 또는 상장폐지 사유 발생  에스앤더블류  
390                  내부결산시점 관리종목 지정 또는 상장폐지 사유 발생     파나진  
391               내부결산시점 관리종목 지정 또는 상장폐지 사유 발생[정]     국순당  
392                  내부결산시점 관리종목 지정 또는 상장폐지 사유 발생    유아이디  
393  내부결산시점 관리종목 지정 또는 상장폐지 사유 발생(자회사의 주요경영사항)[정]     이녹스  

[394 rows x 6 columns]

In [239]:
#저장
# bankrupt_df.to_csv('kind_bankrupt_df.csv')

### bankrupt_df 파일 불러온 후 시간 슬라이싱

In [240]:
# bankrupt = pd.read_csv(r'C:\Users\user\Desktop\code\부실기업\kind_bankrupt_df.csv', index_col=0)

In [241]:
#년도 추출
bankrupt['년'] = bankrupt['시간'].str[:4]

In [242]:
bankrupt.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 394 entries, 0 to 393
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   시간      394 non-null    object
 1   회사명     394 non-null    object
 2   종목코드    394 non-null    int64 
 3   공시제목    394 non-null    object
 4   제출인     386 non-null    object
 5   년       394 non-null    object
dtypes: int64(1), object(5)
memory usage: 21.5+ KB


In [243]:
#dataset.loc[(dataset['occyp_type'] == 'Nan') & (dataset['DAYS_EMPLOYED'] == 0), 'occyp_type'] = 'jobless'

In [244]:
print(train.shape)
print(bankrupt.shape)

(27166, 6)
(394, 6)


### train, bankrupt merge위한 key 만들기 : 종목코드 + 년 

In [245]:
bankrupt['key'] = bankrupt['종목코드'].astype(str) +  bankrupt['년']

In [246]:
train['key'] = train['거래소코드'].astype(str) + train['년'].astype(str)
train_full['key'] = train_full['거래소코드'].astype(str) + train_full['년'].astype(str)

In [247]:
merged = pd.merge(train_full, bankrupt, on = 'key', how = 'outer')
# merged = pd.merge(train_full, bankrupt, on = 'key', how = 'outer')

In [248]:
merged

회사명_x    거래소코드     회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
0      (주)CMG제약  58820.0  2000/12   5.0   NaN     UQ   28990.0   21169.0   
1      (주)CMG제약  58820.0  2001/12   5.0   NaN     UQ   20908.0   16359.0   
2      (주)CMG제약  58820.0  2002/12   5.0   NaN     UQ   15401.0    9880.0   
3      (주)CMG제약  58820.0  2003/12   5.0   NaN     UQ   11063.0    8534.0   
4      (주)CMG제약  58820.0  2004/12   5.0   NaN     UQ    5179.0    3893.0   
...         ...      ...      ...   ...   ...    ...       ...       ...   
27374       NaN      NaN      NaN   NaN   NaN    NaN       NaN       NaN   
27375       NaN      NaN      NaN   NaN   NaN    NaN       NaN       NaN   
27376       NaN      NaN      NaN   NaN   NaN    NaN       NaN       NaN   
27377       NaN      NaN      NaN   NaN   NaN    NaN       NaN       NaN   
27378       NaN      NaN      NaN   NaN   NaN    NaN       NaN       NaN   

       당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA     년_x  \
0       10541.0          4330.0  ...             NaN        NaN  2001.0   
1        2307.0          1829.0  ...             NaN        NaN  2002.0   
2        1436.0           355.0  ...             NaN        NaN  2003.0   
3        1083.0             2.0  ...             NaN        NaN  2004.0   
4         445.0            11.0  ...             NaN        NaN  2005.0   
...         ...             ...  ...             ...        ...     ...   
27374       NaN             NaN  ...             NaN        NaN     NaN   
27375       NaN             NaN  ...             NaN        NaN     NaN   
27376       NaN             NaN  ...             NaN        NaN     NaN   
27377       NaN             NaN  ...             NaN        NaN     NaN   
27378       NaN             NaN  ...             NaN        NaN     NaN   

              key                시간   회사명_y      종목코드          공시제목     제출인  \
0       588202001               NaN     NaN       NaN           NaN     NaN   
1       588202002               NaN     NaN       NaN           NaN     NaN   
2       588202003               NaN     NaN       NaN           NaN     NaN   
3       588202004               NaN     NaN       NaN           NaN     NaN   
4       588202005               NaN     NaN       NaN           NaN     NaN   
...           ...               ...     ...       ...           ...     ...   
27374  1019702015  2015-03-02 18:15  우양에이치씨  101970.0      회생절차개시신청  우양에이치씨   
27375   336002020  2020-11-17 16:01      럭슬   33600.0  [정정]회생절차개시신청      럭슬   
27376   336002020  2020-09-02 15:40      럭슬   33600.0   회생절차개시신청[정]      럭슬   
27377   862502020  2020-07-28 14:54   이노와이즈   86250.0      회생절차개시결정    화신테크   
27378   862502020  2020-05-08 15:03   이노와이즈   86250.0      회생절차개시신청    화신테크   

        년_y  
0       NaN  
1       NaN  
2       NaN  
3       NaN  
4       NaN  
...     ...  
27374  2015  
27375  2020  
27376  2020  
27377  2020  
27378  2020  

[27379 rows x 275 columns]

In [249]:
merged[merged['회사명_x'].isna()]

회사명_x  거래소코드 회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  당좌자산(요약)  \
27357   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27358   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27359   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27360   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27361   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27362   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27363   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27364   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27365   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27366   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27367   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27368   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27369   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27370   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27371   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27372   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27373   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27374   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27375   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27376   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27377   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27378   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   

       현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  년_x         key  \
27357             NaN  ...             NaN        NaN  NaN   318002000   
27358             NaN  ...             NaN        NaN  NaN   318002000   
27359             NaN  ...             NaN        NaN  NaN   318002000   
27360             NaN  ...             NaN        NaN  NaN   318002000   
27361             NaN  ...             NaN        NaN  NaN   338502000   
27362             NaN  ...             NaN        NaN  NaN   333102000   
27363             NaN  ...             NaN        NaN  NaN   333102000   
27364             NaN  ...             NaN        NaN  NaN   133102000   
27365             NaN  ...             NaN        NaN  NaN   283002000   
27366             NaN  ...             NaN        NaN  NaN   283002000   
27367             NaN  ...             NaN        NaN  NaN   283002000   
27368             NaN  ...             NaN        NaN  NaN   192602000   
27369             NaN  ...             NaN        NaN  NaN   540202010   
27370             NaN  ...             NaN        NaN  NaN   801402010   
27371             NaN  ...             NaN        NaN  NaN   372402012   
27372             NaN  ...             NaN        NaN  NaN   454702012   
27373             NaN  ...             NaN        NaN  NaN  1019702015   
27374             NaN  ...             NaN        NaN  NaN  1019702015   
27375             NaN  ...             NaN        NaN  NaN   336002020   
27376             NaN  ...             NaN        NaN  NaN   336002020   
27377             NaN  ...             NaN        NaN  NaN   862502020   
27378             NaN  ...             NaN        NaN  NaN   862502020   

                     시간      회사명_y      종목코드                          공시제목  \
27357  2000-12-20 16:17       ST&I   31800.0                    회사정리절차종결결정   
27358  2000-11-23 10:19       ST&I   31800.0                    회사정리절차종결신청   
27359  2000-03-28 00:00       ST&I   31800.0    회사정리절차개시결정(씨티아이반도체(주) (1))   
27360  2000-03-28 00:00       ST&I   31800.0    회사정리절차개시결정(씨티아이반도체(주) (2))   
27361  2000-08-07 15:44      지노시스템   33850.0                 화의채무변제완료보고서제출   
27362  2000-06-29 10:33        엠투엔   33310.0                 화의채무변제완료보고서제출   
27363  2

In [250]:
print('train에 반영되지않은 부도회사 명 : ','\n', merged[merged['회사명_x'].isna()]['회사명_y'].unique())
print('-------------------------------------------------------------------')
print('train에 반영되지않은 부도회사 코드 : ', '\n', merged[merged['소속코드'].isna()]['종목코드'].unique())
print('-------------------------------------------------------------------')
print('train에 반영되지않은 부도회사 계 : ', merged[merged['회사명_x'].isna()]['회사명_y'].nunique())

train에 반영되지않은 부도회사 명 :  
 ['ST&I' '지노시스템' '엠투엔' '아진산업' '에이치엘비' '엔케이바이오' 'GK파워' '디보스' '평안물산'
 '에이프로테크놀로지' '우양에이치씨' '럭슬' '이노와이즈']
-------------------------------------------------------------------
train에 반영되지않은 부도회사 코드 :  
 [ 31800.  33850.  33310.  13310.  28300.  19260.  54020.  80140.  37240.
  45470. 101970.  33600.  86250.]
-------------------------------------------------------------------
train에 반영되지않은 부도회사 계 :  13


## train에 반영되지않은 부도기업 13개 공시제목 채워넣기<br>
<span style="color:yellow">처리한 내역</span><br>
-31800.0 	(주)에스티앤아이<br>
-33850.0    (주)지노시스템<br>
-54020.0    (주)지케이파워<br>
-37240.0    평안물산(주)<br>
-45470.0    (주)에이프로테크놀로지<br>
-101970.0   우양에이치씨(주)<br>
-33600.0    럭슬(주)<br>
-86250.0    (주)화신테크<br>
<br>
-28300.0    에이치엘비(주)	<br>
-19260.0    (주)엔케이바이오<br>
-80140.0    (주)디보스<br>

<span style="color:red">**특이사항**</span><br>
-33310.0    (주)엠투엔 00년에 채무변제완료 후 은행거래 재개 -> 부도기업 아님으로 판단<br>
-13310.0    아진산업(주) -> 회사정리절차개시결정 후 20년간 영업중. 부도기업인지 아닌지 고려해봐야함

### st&i 31800.0

In [251]:
merged.loc[merged['거래소코드']==31800.0]

회사명_x    거래소코드     회계년도  소속코드       상장폐지일 감사의견코드  자산총계(요약)  \
9016  (주)에스티앤아이  31800.0  2000/12   4.0  2009/07/01     UQ   39665.0   
9017  (주)에스티앤아이  31800.0  2001/12   4.0  2009/07/01     UQ   34205.0   
9018  (주)에스티앤아이  31800.0  2002/12   4.0  2009/07/01     UQ   67242.0   
9019  (주)에스티앤아이  31800.0  2003/12   4.0  2009/07/01     UQ   51446.0   
9020  (주)에스티앤아이  31800.0  2004/12   4.0  2009/07/01     UQ   42000.0   
9021  (주)에스티앤아이  31800.0  2005/12   4.0  2009/07/01     UQ   34047.0   
9022  (주)에스티앤아이  31800.0  2006/12   4.0  2009/07/01     UQ   57281.0   
9023  (주)에스티앤아이  31800.0  2007/12   4.0  2009/07/01     UQ   65077.0   
9024  (주)에스티앤아이  31800.0  2008/12   4.0  2009/07/01     UQ    8326.0   

      유동자산(요약)  당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  \
9016    3256.0    2928.0           511.0  ...             NaN        NaN   
9017    2258.0    1407.0            61.0  ...             NaN        NaN   
9018   37320.0   12111.0          1054.0  ...             NaN        NaN   
9019   17927.0   10882.0          2569.0  ...             NaN        NaN   
9020   11661.0   10886.0          9555.0  ...             NaN        NaN   
9021    6314.0    4646.0           150.0  ...             NaN        NaN   
9022   16155.0   13271.0          1507.0  ...             NaN        NaN   
9023   26264.0   24626.0           204.0  ...          -75.77        0.0   
9024    1243.0    1243.0            36.0  ...         -116.99        NaN   

         년_x        key   시간  회사명_y  종목코드  공시제목  제출인  년_y  
9016  2001.0  318002001  NaN    NaN   NaN   NaN  NaN  NaN  
9017  2002.0  318002002  NaN    NaN   NaN   NaN  NaN  NaN  
9018  2003.0  318002003  NaN    NaN   NaN   NaN  NaN  NaN  
9019  2004.0  318002004  NaN    NaN   NaN   NaN  NaN  NaN  
9020  2005.0  318002005  NaN    NaN   NaN   NaN  NaN  NaN  
9021  2006.0  318002006  NaN    NaN   NaN   NaN  NaN  NaN  
9022  2007.0  318002007  NaN    NaN   NaN   NaN  NaN  NaN  
9023  2008.0  318002008  NaN    NaN   NaN   NaN  NaN  NaN  
9024  2009.0  318002009  NaN    NaN   NaN   NaN  NaN  NaN  

[9 rows x 275 columns]

In [252]:
merged.loc[merged['종목코드']==31800.0]

회사명_x  거래소코드 회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  당좌자산(요약)  \
27357   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27358   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27359   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27360   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   

       현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  년_x        key  \
27357             NaN  ...             NaN        NaN  NaN  318002000   
27358             NaN  ...             NaN        NaN  NaN  318002000   
27359             NaN  ...             NaN        NaN  NaN  318002000   
27360             NaN  ...             NaN        NaN  NaN  318002000   

                     시간  회사명_y     종목코드                        공시제목     제출인  \
27357  2000-12-20 16:17   ST&I  31800.0                  회사정리절차종결결정  에스티앤아이   
27358  2000-11-23 10:19   ST&I  31800.0                  회사정리절차종결신청  에스티앤아이   
27359  2000-03-28 00:00   ST&I  31800.0  회사정리절차개시결정(씨티아이반도체(주) (1))     NaN   
27360  2000-03-28 00:00   ST&I  31800.0  회사정리절차개시결정(씨티아이반도체(주) (2))     NaN   

        년_y  
27357  2000  
27358  2000  
27359  2000  
27360  2000  

[4 rows x 275 columns]

In [253]:
merged.loc[merged['key']=='318002000', '공시제목'] = '회사정리절차종결결정'

### **엠투엔** 33310.0 -> 부도기업 아닌걸로 판단 

In [254]:
merged.loc[merged['거래소코드']==33310.0]

회사명_x    거래소코드     회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
10414  (주)엠투엔  33310.0  2000/12   5.0   NaN     QG   21993.0    9456.0   
10415  (주)엠투엔  33310.0  2001/12   5.0   NaN     UQ   23635.0    9988.0   
10416  (주)엠투엔  33310.0  2002/12   5.0   NaN     UQ   29815.0   15254.0   
10417  (주)엠투엔  33310.0  2003/12   5.0   NaN     UQ   23895.0   14267.0   
10418  (주)엠투엔  33310.0  2004/12   5.0   NaN     UQ   24814.0   14154.0   
10419  (주)엠투엔  33310.0  2005/12   5.0   NaN     UQ   25800.0   14601.0   
10420  (주)엠투엔  33310.0  2006/12   5.0   NaN     UQ   28862.0   17819.0   
10421  (주)엠투엔  33310.0  2007/12   5.0   NaN     UQ   61285.0   18852.0   
10422  (주)엠투엔  33310.0  2008/12   5.0   NaN     UQ   73832.0   24728.0   
10423  (주)엠투엔  33310.0  2009/12   5.0   NaN     UQ   67139.0   21664.0   
10424  (주)엠투엔  33310.0  2010/12   5.0   NaN     UQ   69463.0   21189.0   
10425  (주)엠투엔  33310.0  2011/12   5.0   NaN     UQ   73308.0   21803.0   
10426  (주)엠투엔  33310.0  2012/12   5.0   NaN     UQ   55697.0   12941.0   
10427  (주)엠투엔  33310.0  2013/12   5.0   NaN     UQ   55332.0   10015.0   
10428  (주)엠투엔  33310.0  2014/12   5.0   NaN     UQ   64814.0    9783.0   
10429  (주)엠투엔  33310.0  2015/12   5.0   NaN     UQ   68935.0    7511.0   
10430  (주)엠투엔  33310.0  2016/12   5.0   NaN     UQ   74834.0    8390.0   
10431  (주)엠투엔  33310.0  2017/12   5.0   NaN     UQ   78823.0    8081.0   
10432  (주)엠투엔  33310.0  2018/12   5.0   NaN     UQ   87009.0   13515.0   
10433  (주)엠투엔  33310.0  2019/12   5.0   NaN     UQ   90578.0   10104.0   
10434  (주)엠투엔  33310.0  2020/12   5.0   NaN     UQ  112327.0   13261.0   

       당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA     년_x  \
10414    5107.0             4.0  ...             NaN        NaN  2001.0   
10415    5819.0           681.0  ...             NaN        NaN  2002.0   
10416    8024.0           383.0  ...             NaN        NaN  2003.0   
10417    6723.0           378.0  ...             NaN        NaN  2004.0   
10418    6537.0          1071.0  ...             NaN        NaN  2005.0   
10419    7325.0           997.0  ...             NaN        NaN  2006.0   
10420    9946.0          1343.0  ...             NaN        NaN  2007.0   
10421   13862.0          3770.0  ...          115.14      86.41  2008.0   
10422   10373.0            91.0  ...          224.87       9.46  2009.0   
10423   12380.0          2726.0  ...           82.27      41.78  2010.0   
10424   13430.0           427.0  ...          202.69      18.85  2011.0   
10425   12206.0           399.0  ...          173.84      28.78  2012.0   
10426   11161.0            48.0  ...          225.57      11.56  2013.0   
10427    7458.0             3.0  ...          322.54       8.87  2014.0   
10428    7341.0            11.0  ...          270.35      11.11  2015.0   
10429    4855.0             0.0  ...          123.75      27.70  2016.0   
10430    6276.0           752.0  ...           96.56      33.22  2017.0   
10431    6148.0           633.0  ...           65.15      41.58  2018.0   
10432    9845.0           618.0  ...           63.10      48.75  2019.0   
10433    8118.0          1733.0  ...           47.43      88.02  2020.0   
10434   11612.0          4825.0  ...           -1.52       0.00  2021.0   

             key   시간  회사명_y  종목코드  공시제목  제출인  년_y  
10414  333102001  NaN    NaN   NaN   NaN  NaN  NaN  
10415  333102002  NaN    NaN   NaN   NaN  NaN  NaN  
10416  333102003  NaN    NaN   NaN   NaN  NaN  NaN  
10417  333102004  NaN    NaN   NaN   NaN  NaN  NaN  
10418  333102005  NaN    NaN   NaN   NaN  NaN  NaN  
10419  333102006  NaN    NaN   NaN   NaN  NaN  NaN  
10420  333102007  NaN    NaN   NaN   NaN  NaN  NaN  
10421  333102008  NaN    NaN   NaN   NaN  NaN  NaN  
10422  333102009  NaN    NaN   NaN   NaN  NaN  NaN  
10423  333102010  NaN    NaN   NaN   NaN  NaN  NaN  
10424  333102011  NaN    NaN   NaN   NaN  NaN  NaN  
10425  333102012  NaN    NaN   NaN   NaN  NaN  NaN  
10426  333102013  NaN    NaN   NaN   Na

In [255]:
merged[merged['종목코드']==33310.0]

회사명_x  거래소코드 회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  당좌자산(요약)  \
27362   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27363   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   

       현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  년_x        key  \
27362             NaN  ...             NaN        NaN  NaN  333102000   
27363             NaN  ...             NaN        NaN  NaN  333102000   

                     시간  회사명_y     종목코드             공시제목  제출인   년_y  
27362  2000-06-29 10:33    엠투엔  33310.0    화의채무변제완료보고서제출  엠투엔  2000  
27363  2000-01-31 00:00    엠투엔  33310.0  은행거래재개((주)우진산전)  NaN  2000  

[2 rows x 275 columns]

In [256]:
merged.loc[merged['key'] == '333102021', '공시제목'] = '화의채무변제완료보고서제출'

### 지노 33850.0 화의채무변제완료보고서제출

In [257]:
merged.loc[merged['거래소코드'] == 33850.0]

회사명_x    거래소코드     회계년도  소속코드       상장폐지일 감사의견코드  자산총계(요약)  \
14214  (주)지노시스템  33850.0  2000/12   4.0  2011/05/07     QG   13655.0   
14215  (주)지노시스템  33850.0  2001/12   4.0  2011/05/07     UQ   22179.0   
14216  (주)지노시스템  33850.0  2002/12   4.0  2011/05/07     UQ   25466.0   
14217  (주)지노시스템  33850.0  2003/12   4.0  2011/05/07     UQ   26862.0   
14218  (주)지노시스템  33850.0  2004/12   4.0  2011/05/07     UQ   16319.0   
14219  (주)지노시스템  33850.0  2005/12   4.0  2011/05/07     UQ   19363.0   
14220  (주)지노시스템  33850.0  2006/12   4.0  2011/05/07     UQ   22226.0   
14221  (주)지노시스템  33850.0  2007/12   4.0  2011/05/07     UQ   30430.0   
14222  (주)지노시스템  33850.0  2008/12   4.0  2011/05/07     UQ   26845.0   
14223  (주)지노시스템  33850.0  2009/12   4.0  2011/05/07     UQ   20577.0   
14224  (주)지노시스템  33850.0  2010/12   4.0  2011/05/07     DS   34650.0   

       유동자산(요약)  당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  \
14214    8846.0    7485.0          1919.0  ...             NaN        NaN   
14215   15593.0   14762.0          2219.0  ...             NaN        NaN   
14216   17229.0   15134.0          2891.0  ...             NaN        NaN   
14217   17129.0   16437.0          1644.0  ...             NaN        NaN   
14218    8982.0    8494.0            41.0  ...             NaN        NaN   
14219    7509.0    7218.0           174.0  ...             NaN        NaN   
14220   13669.0   13502.0          5023.0  ...             NaN        NaN   
14221   17580.0   17538.0          4681.0  ...          -42.44        0.0   
14222   12301.0   10110.0          2261.0  ...          -49.88        NaN   
14223    7062.0    6347.0          3359.0  ...          -69.36        NaN   
14224   23288.0   18166.0           365.0  ...          -29.04        NaN   

          년_x        key   시간  회사명_y  종목코드  공시제목  제출인  년_y  
14214  2001.0  338502001  NaN    NaN   NaN   NaN  NaN  NaN  
14215  2002.0  338502002  NaN    NaN   NaN   NaN  NaN  NaN  
14216  2003.0  338502003  NaN    NaN   NaN   NaN  NaN  NaN  
14217  2004.0  338502004  NaN    NaN   NaN   NaN  NaN  NaN  
14218  2005.0  338502005  NaN    NaN   NaN   NaN  NaN  NaN  
14219  2006.0  338502006  NaN    NaN   NaN   NaN  NaN  NaN  
14220  2007.0  338502007  NaN    NaN   NaN   NaN  NaN  NaN  
14221  2008.0  338502008  NaN    NaN   NaN   NaN  NaN  NaN  
14222  2009.0  338502009  NaN    NaN   NaN   NaN  NaN  NaN  
14223  2010.0  338502010  NaN    NaN   NaN   NaN  NaN  NaN  
14224  2011.0  338502011  NaN    NaN   NaN   NaN  NaN  NaN  

[11 rows x 275 columns]

In [258]:
merged.loc[merged['종목코드'] == 33850.0]

회사명_x  거래소코드 회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  당좌자산(요약)  \
27361   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   

       현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  년_x        key  \
27361             NaN  ...             NaN        NaN  NaN  338502000   

                     시간  회사명_y     종목코드           공시제목    제출인   년_y  
27361  2000-08-07 15:44  지노시스템  33850.0  화의채무변제완료보고서제출  지노시스템  2000  

[1 rows x 275 columns]

In [259]:
merged.loc[merged['key'] == '338502011', '공시제목'] = '화의채무변제완료보고서제출'

### **아진산업** 13310.0 -다시 보기 NaN친구 -> 회사정리절차개시결정 후 20년간 영업중 고려해봐야함

In [260]:
merged.loc[merged['거래소코드'] == 13310.0]

회사명_x    거래소코드     회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
22951  아진산업(주)  13310.0  2002/12   5.0   NaN     UQ   22950.0    8013.0   
22952  아진산업(주)  13310.0  2003/12   5.0   NaN     UQ   21161.0    7393.0   
22953  아진산업(주)  13310.0  2004/12   5.0   NaN     UQ   20043.0    4902.0   
22954  아진산업(주)  13310.0  2005/12   5.0   NaN     UQ   34809.0   11729.0   
22955  아진산업(주)  13310.0  2006/12   5.0   NaN     UQ   37867.0    6117.0   
22956  아진산업(주)  13310.0  2007/12   5.0   NaN     UQ   45183.0    8901.0   
22957  아진산업(주)  13310.0  2008/12   5.0   NaN     UQ   91325.0   17752.0   
22958  아진산업(주)  13310.0  2009/12   5.0   NaN     UQ  110853.0   32332.0   
22959  아진산업(주)  13310.0  2010/12   5.0   NaN     UQ  150757.0   54306.0   
22960  아진산업(주)  13310.0  2011/12   5.0   NaN     UQ  187676.0   66664.0   
22961  아진산업(주)  13310.0  2012/12   5.0   NaN     UQ  196791.0   71939.0   
22962  아진산업(주)  13310.0  2013/12   5.0   NaN     UQ  219825.0   78530.0   
22963  아진산업(주)  13310.0  2014/12   5.0   NaN     UQ  231295.0   75232.0   
22964  아진산업(주)  13310.0  2015/12   5.0   NaN     UQ  272481.0   77752.0   
22965  아진산업(주)  13310.0  2016/12   5.0   NaN     UQ  306968.0   84434.0   
22966  아진산업(주)  13310.0  2017/12   5.0   NaN     UQ  346149.0   89888.0   
22967  아진산업(주)  13310.0  2018/12   5.0   NaN     UQ  386491.0   86217.0   
22968  아진산업(주)  13310.0  2019/12   5.0   NaN     UQ  447355.0  148487.0   
22969  아진산업(주)  13310.0  2020/12   5.0   NaN     UQ  432699.0  155888.0   

       당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA     년_x  \
22951    7325.0           656.0  ...             NaN        NaN  2003.0   
22952    6661.0             9.0  ...             NaN        NaN  2004.0   
22953    4035.0          1665.0  ...             NaN        NaN  2005.0   
22954   10733.0          6520.0  ...             NaN        NaN  2006.0   
22955    4882.0             1.0  ...             NaN        NaN  2007.0   
22956    7359.0           466.0  ...        12002.04       1.45  2008.0   
22957   15222.0           272.0  ...        11623.02       3.74  2009.0   
22958   29509.0           246.0  ...        21307.55       3.48  2010.0   
22959   46940.0          5377.0  ...        23644.77       2.74  2011.0   
22960   64329.0           434.0  ...        24032.74       2.20  2012.0   
22961   68804.0           267.0  ...        28550.39       1.72  2013.0   
22962   73115.0           219.0  ...         2560.18       5.30  2014.0   
22963   71651.0           186.0  ...         4817.29       2.28  2015.0   
22964   74647.0           296.0  ...         4736.09       3.80  2016.0   
22965   80739.0           559.0  ...         2273.28       7.31  2017.0   
22966   81712.0           284.0  ...         1936.64       8.84  2018.0   
22967   78107.0           953.0  ...          261.52      25.84  2019.0   
22968  137282.0         13361.0  ...         1578.98       5.10  2020.0   
22969  142965.0         22910.0  ...         1172.59       5.59  2021.0   

             key   시간  회사명_y  종목코드  공시제목  제출인  년_y  
22951  133102003  NaN    NaN   NaN   NaN  NaN  NaN  
22952  133102004  NaN    NaN   NaN   NaN  NaN  NaN  
22953  133102005  NaN    NaN   NaN   NaN  NaN  NaN  
22954  133102006  NaN    NaN   NaN   NaN  NaN  NaN  
22955  133102007  NaN    NaN   NaN   NaN  NaN  NaN  
22956  133102008  NaN    NaN   NaN   NaN  NaN  NaN  
22957  133102009  NaN    NaN   NaN   NaN  NaN  NaN  
22958  133102010  NaN    NaN   NaN   NaN  NaN  NaN  
22959  133102011  NaN    NaN   NaN   NaN  NaN  NaN  
22960  133102012  NaN    NaN   NaN   NaN  NaN  NaN  
22961  133102013  NaN    NaN   NaN   NaN  NaN  NaN  
22962  133102014  NaN    NaN   NaN   NaN  NaN  NaN  
22963  133102015  NaN    NaN   NaN   NaN  NaN  NaN  
22964  133102016  NaN    NaN   NaN   NaN  NaN  NaN  
22965  133102017  NaN    NaN   NaN   NaN  NaN  NaN  
22966  133102018  NaN    NaN   NaN   NaN  NaN  NaN  
22967  133102019  NaN    NaN   NaN   NaN  NaN  NaN  
22968  133102020  NaN    NaN   NaN   NaN  NaN  NaN  


In [261]:
merged.loc[merged['종목코드'] == 13310.0]

회사명_x  거래소코드 회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  당좌자산(요약)  \
27364   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   

       현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  년_x        key  \
27364             NaN  ...             NaN        NaN  NaN  133102000   

                     시간  회사명_y     종목코드                 공시제목  제출인   년_y  
27364  2000-03-31 00:00   아진산업  13310.0  회사정리절차개시결정(아진산업(주))  NaN  2000  

[1 rows x 275 columns]

In [262]:
merged.loc[merged['key'] == '133102021', '공시제목'] = '회사정리절차개시결정(아진산업(주))'

### **에이치엘비** 28300.0 2002 회사정리절차종결 BUT 2020까지 회사운영중

In [263]:
merged.loc[merged['거래소코드'] == 28300.0]

회사명_x    거래소코드     회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
23576  에이치엘비(주)  28300.0  2000/12   5.0   NaN     UQ   22460.0    3362.0   
23577  에이치엘비(주)  28300.0  2001/12   5.0   NaN     UQ   17974.0    2380.0   
23578  에이치엘비(주)  28300.0  2001/12   5.0   NaN     UQ   17974.0    2380.0   
23579  에이치엘비(주)  28300.0  2002/12   5.0   NaN     UQ   16407.0    2497.0   
23580  에이치엘비(주)  28300.0  2003/12   5.0   NaN     QG   11762.0     726.0   
23581  에이치엘비(주)  28300.0  2004/12   5.0   NaN     UQ    2347.0    1768.0   
23582  에이치엘비(주)  28300.0  2005/12   5.0   NaN     UQ   19044.0    7618.0   
23583  에이치엘비(주)  28300.0  2006/12   5.0   NaN     UQ   27051.0   15420.0   
23584  에이치엘비(주)  28300.0  2007/12   5.0   NaN     UQ   43462.0   27231.0   
23585  에이치엘비(주)  28300.0  2008/12   5.0   NaN     UQ   50147.0   10165.0   
23586  에이치엘비(주)  28300.0  2009/12   5.0   NaN     UQ   53819.0   18614.0   
23587  에이치엘비(주)  28300.0  2010/12   5.0   NaN     UQ   35552.0   13134.0   
23588  에이치엘비(주)  28300.0  2011/12   5.0   NaN     UQ   34276.0    9327.0   
23589  에이치엘비(주)  28300.0  2012/12   5.0   NaN     UQ   31684.0    7171.0   
23590  에이치엘비(주)  28300.0  2013/12   5.0   NaN     UQ   33835.0   16999.0   
23591  에이치엘비(주)  28300.0  2014/12   5.0   NaN     UQ   51958.0   32847.0   
23592  에이치엘비(주)  28300.0  2015/12   5.0   NaN     UQ   91734.0   20424.0   
23593  에이치엘비(주)  28300.0  2016/12   5.0   NaN     UQ   87304.0   15912.0   
23594  에이치엘비(주)  28300.0  2017/12   5.0   NaN     UQ  108127.0   16558.0   
23595  에이치엘비(주)  28300.0  2018/12   5.0   NaN     UQ  238044.0   99004.0   
23596  에이치엘비(주)  28300.0  2019/12   5.0   NaN     UQ  494081.0   40641.0   
23597  에이치엘비(주)  28300.0  2020/12   5.0   NaN     UQ  791486.0  173521.0   

       당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA     년_x  \
23576    1775.0           216.0  ...             NaN        NaN  2001.0   
23577    1243.0             3.0  ...             NaN        NaN  2002.0   
23578    1243.0             3.0  ...             NaN        NaN  2002.0   
23579    1990.0            30.0  ...             NaN        NaN  2003.0   
23580     645.0           303.0  ...             NaN        NaN  2004.0   
23581    1768.0            15.0  ...             NaN        NaN  2005.0   
23582    7318.0          3858.0  ...             NaN        NaN  2006.0   
23583   15063.0          7998.0  ...             NaN        NaN  2007.0   
23584   27209.0         13265.0  ...         -435.79       0.00  2008.0   
23585    9613.0           169.0  ...         -124.04        NaN  2009.0   
23586   18039.0          1445.0  ...          -14.91        NaN  2010.0   
23587   13042.0          1223.0  ...          -13.22        NaN  2011.0   
23588    9291.0          2028.0  ...           45.38      60.61  2012.0   
23589    7088.0           903.0  ...          -57.77       0.00  2013.0   
23590   12459.0          1049.0  ...         -138.15       0.00  2014.0   
23591   25174.0         10044.0  ...           93.81      88.30  2015.0   
23592   15118.0          3492.0  ...          -25.20       0.00  2016.0   
23593   12058.0          8018.0  ...          -87.23       0.00  2017.0   
23594   12415.0          6970.0  ...         -145.78       0.00  2018.0   
23595   95948.0         13746.0  ...           64.08    1270.27  2019.0   
23596   36613.0         13329.0  ...          -89.08       0.00  2020.0   
23597  169435.0        154000.0  ...          -18.00       0.00  2021.0   

             key                시간  회사명_y     종목코드        공시제목    제출인   년_y  
23576  283002001               NaN    NaN      NaN         NaN    NaN   NaN  
23577  283002002  2002-05-21 18:16  에이치엘비  28300.0  회사정리절차종결결정  에이치엘비  2002  
23578  283002002  2002-04-17 17:42  에이치엘비  28300.0  회사정리절차종결신청  에이치엘비  2002  
23579  283002003               NaN    NaN      NaN         NaN    NaN   NaN  
23580  283002004               NaN    NaN      NaN         NaN    NaN   NaN  
23581  283002005               NaN    NaN      NaN         NaN    N

In [264]:
merged.loc[merged['종목코드'] == 28300.0]

회사명_x    거래소코드     회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
23577  에이치엘비(주)  28300.0  2001/12   5.0   NaN     UQ   17974.0    2380.0   
23578  에이치엘비(주)  28300.0  2001/12   5.0   NaN     UQ   17974.0    2380.0   
27365       NaN      NaN      NaN   NaN   NaN    NaN       NaN       NaN   
27366       NaN      NaN      NaN   NaN   NaN    NaN       NaN       NaN   
27367       NaN      NaN      NaN   NaN   NaN    NaN       NaN       NaN   

       당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA     년_x  \
23577    1243.0             3.0  ...             NaN        NaN  2002.0   
23578    1243.0             3.0  ...             NaN        NaN  2002.0   
27365       NaN             NaN  ...             NaN        NaN     NaN   
27366       NaN             NaN  ...             NaN        NaN     NaN   
27367       NaN             NaN  ...             NaN        NaN     NaN   

             key                시간  회사명_y     종목코드                     공시제목  \
23577  283002002  2002-05-21 18:16  에이치엘비  28300.0               회사정리절차종결결정   
23578  283002002  2002-04-17 17:42  에이치엘비  28300.0               회사정리절차종결신청   
27365  283002000  2000-03-31 00:00  에이치엘비  28300.0          은행거래재개(국제정공(주))   
27366  283002000  2000-02-09 00:00  에이치엘비  28300.0  회사정리절차개시결정(국제정공(주) (1))   
27367  283002000  2000-02-09 00:00  에이치엘비  28300.0  회사정리절차개시결정(국제정공(주) (2))   

         제출인   년_y  
23577  에이치엘비  2002  
23578  에이치엘비  2002  
27365    NaN  2000  
27366    NaN  2000  
27367    NaN  2000  

[5 rows x 275 columns]

In [265]:
merged[merged['종목코드']==28300.0]

회사명_x    거래소코드     회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
23577  에이치엘비(주)  28300.0  2001/12   5.0   NaN     UQ   17974.0    2380.0   
23578  에이치엘비(주)  28300.0  2001/12   5.0   NaN     UQ   17974.0    2380.0   
27365       NaN      NaN      NaN   NaN   NaN    NaN       NaN       NaN   
27366       NaN      NaN      NaN   NaN   NaN    NaN       NaN       NaN   
27367       NaN      NaN      NaN   NaN   NaN    NaN       NaN       NaN   

       당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA     년_x  \
23577    1243.0             3.0  ...             NaN        NaN  2002.0   
23578    1243.0             3.0  ...             NaN        NaN  2002.0   
27365       NaN             NaN  ...             NaN        NaN     NaN   
27366       NaN             NaN  ...             NaN        NaN     NaN   
27367       NaN             NaN  ...             NaN        NaN     NaN   

             key                시간  회사명_y     종목코드                     공시제목  \
23577  283002002  2002-05-21 18:16  에이치엘비  28300.0               회사정리절차종결결정   
23578  283002002  2002-04-17 17:42  에이치엘비  28300.0               회사정리절차종결신청   
27365  283002000  2000-03-31 00:00  에이치엘비  28300.0          은행거래재개(국제정공(주))   
27366  283002000  2000-02-09 00:00  에이치엘비  28300.0  회사정리절차개시결정(국제정공(주) (1))   
27367  283002000  2000-02-09 00:00  에이치엘비  28300.0  회사정리절차개시결정(국제정공(주) (2))   

         제출인   년_y  
23577  에이치엘비  2002  
23578  에이치엘비  2002  
27365    NaN  2000  
27366    NaN  2000  
27367    NaN  2000  

[5 rows x 275 columns]

### **엔케이바이오** 19260.0 ->채무변제완료 및 은행거래 재개

In [266]:
merged.loc[merged['거래소코드'] == 19260.0]

회사명_x    거래소코드     회계년도  소속코드       상장폐지일 감사의견코드  자산총계(요약)  \
10017  (주)엔케이바이오  19260.0  2000/12   4.0  2012/09/05     UQ   31785.0   
10018  (주)엔케이바이오  19260.0  2001/12   4.0  2012/09/05     UQ   26915.0   
10019  (주)엔케이바이오  19260.0  2002/12   4.0  2012/09/05     UQ   24184.0   
10020  (주)엔케이바이오  19260.0  2003/12   4.0  2012/09/05     UQ   23685.0   
10021  (주)엔케이바이오  19260.0  2004/12   4.0  2012/09/05     UQ   37651.0   
10022  (주)엔케이바이오  19260.0  2005/12   4.0  2012/09/05     UQ   43491.0   
10023  (주)엔케이바이오  19260.0  2006/12   4.0  2012/09/05     UQ   54911.0   
10024  (주)엔케이바이오  19260.0  2007/12   4.0  2012/09/05     UQ   40157.0   
10025  (주)엔케이바이오  19260.0  2008/12   4.0  2012/09/05     UQ   48850.0   
10026  (주)엔케이바이오  19260.0  2009/12   4.0  2012/09/05     UQ   46809.0   
10027  (주)엔케이바이오  19260.0  2010/12   4.0  2012/09/05     UQ   48744.0   
10028  (주)엔케이바이오  19260.0  2011/12   4.0  2012/09/05     QU   53101.0   

       유동자산(요약)  당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  \
10017    7360.0    5442.0           540.0  ...             NaN        NaN   
10018    5537.0    4495.0           719.0  ...             NaN        NaN   
10019    4948.0    3687.0           464.0  ...             NaN        NaN   
10020    7548.0    6099.0          1321.0  ...             NaN        NaN   
10021   10036.0    8051.0          1704.0  ...             NaN        NaN   
10022   12572.0   10307.0          3095.0  ...             NaN        NaN   
10023   20037.0   18054.0          7822.0  ...             NaN        NaN   
10024   10451.0    8221.0          1348.0  ...         -314.91       0.00   
10025    6408.0    6017.0          1430.0  ...         -230.81       0.00   
10026    6424.0    5890.0           892.0  ...         -127.80       0.00   
10027   15419.0   14573.0          1878.0  ...          -55.33        NaN   
10028   16161.0   15557.0          2892.0  ...           58.28      27.55   

          년_x        key                시간   회사명_y     종목코드           공시제목  \
10017  2001.0  192602001  2001-02-22 18:34  엔케이바이오  19260.0  화의채무변제완료보고서제출   
10018  2002.0  192602002               NaN     NaN      NaN            NaN   
10019  2003.0  192602003               NaN     NaN      NaN            NaN   
10020  2004.0  192602004               NaN     NaN      NaN            NaN   
10021  2005.0  192602005               NaN     NaN      NaN            NaN   
10022  2006.0  192602006               NaN     NaN      NaN            NaN   
10023  2007.0  192602007               NaN     NaN      NaN            NaN   
10024  2008.0  192602008               NaN     NaN      NaN            NaN   
10025  2009.0  192602009               NaN     NaN      NaN            NaN   
10026  2010.0  192602010               NaN     NaN      NaN            NaN   
10027  2011.0  192602011               NaN     NaN      NaN            NaN   
10028  2012.0  192602012               NaN     NaN      NaN            NaN   

       제출인   년_y  
10017   셀텍  2001  
10018  NaN   NaN  
10019  NaN   NaN  
10020  NaN   NaN  
10021  NaN   NaN  
10022  NaN   NaN  
10023  NaN   NaN  
10024  NaN   NaN  
10025  NaN   NaN  
10026  NaN   NaN  
10027  NaN   NaN  
10028  NaN   NaN  

[12 rows x 275 columns]

In [267]:
merged.loc[merged['종목코드'] == 19260.0]

회사명_x    거래소코드     회계년도  소속코드       상장폐지일 감사의견코드  자산총계(요약)  \
10017  (주)엔케이바이오  19260.0  2000/12   4.0  2012/09/05     UQ   31785.0   
27368        NaN      NaN      NaN   NaN         NaN    NaN       NaN   

       유동자산(요약)  당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  \
10017    7360.0    5442.0           540.0  ...             NaN        NaN   
27368       NaN       NaN             NaN  ...             NaN        NaN   

          년_x        key                시간   회사명_y     종목코드           공시제목  \
10017  2001.0  192602001  2001-02-22 18:34  엔케이바이오  19260.0  화의채무변제완료보고서제출   
27368     NaN  192602000  2000-03-23 00:00  엔케이바이오  19260.0  은행거래재개((주)한올)   

       제출인   년_y  
10017   셀텍  2001  
27368  NaN  2000  

[2 rows x 275 columns]

In [268]:
merged.loc[merged['key'] == 19260.0]

Empty DataFrame
Columns: [회사명_x, 거래소코드, 회계년도, 소속코드, 상장폐지일, 감사의견코드, 자산총계(요약), 유동자산(요약), 당좌자산(요약), 현금 및 현금성자산(요약), 단기투자자산(요약), 단기예금(요약), 단기매매증권(요약), 단기대여금(요약), 기타단기투자자산(요약), 매출채권(요약), *할인어음 또는 배서어음(요약), 기타당좌자산(요약), 재고자산(요약), 상품(요약), 제품(요약), 반제품(요약), 재공품(요약), 원재료(요약), 기타재고자산(요약), 임대주택자산(요약), 비유동자산(요약), 투자자산(요약), *장기금융상품(요약), *투자유가증권(장기투자증권)(요약), 유형자산(요약), 토지, 건설중인자산, 건물, 기계장치, 차량운반구, 렌탈자산, 설비자산, 무형자산(요약), 기타비유동자산(요약), 이연자산(요약), 부채총계(요약), 유동부채(요약), 매입채무(요약), 단기차입금(요약), 유동성장기부채(요약), 기타유동부채(요약), 비유동부채(요약), 사채(요약), 장기차입금(요약), 제충당금(요약), 기타비유동부채(요약), 이연부채(요약), 자본총계(요약), 자본금(요약), 자본잉여금(요약), 자본조정(요약), 기타포괄손익누계액(요약), 이익잉여금(요약), *미처분이익잉여금 및 차기이월미처분이익잉여금(요약), *당기순이익(요약), 부채와자본총계(요약), 매출액(요약), 매출원가(요약), 매출총이익(요약), 판매비와 관리비(요약), 급료, 퇴직급여(요약), 복리후생비(요약), 세금과공과(요약), 임차료(요약), 감가상각비, 연구비, 기타 판매비와 관리비(요약), 영업이익(요약), 영업외수익(요약), 이자수익(요약), 배당금수익(요약), 외환차익(요약), 외화환산이익(요약), 지분법이익(요약), 기타영업외수익(요약), 영업외비용(요약), 이자비용(요약), 외환차손(요약), 외화환산손실(요약), 지분법손실(요약), 기타영업외비용(요약), 법인세비용차감전(계속사업)손익(요약), (계속사업손익)법인세비용(요약), 계속사업이익(요약), 중단사업이익(요약), *법인세효과(요약), 당기순이익(요약), 주당계속사업이익(요약), 주당순이익(요약), 희석화주당계속사업이익(요약), 희석화주당순이익(요약), CPA수정후 당기순이익(요약), *주당경상이익(2007년 이전 발생)(요약), ...]
Index: []

[0 rows x 275 columns]

### GK파워 54020.0

In [269]:
merged.loc[merged['거래소코드'] == 54020.0]

회사명_x    거래소코드     회계년도  소속코드       상장폐지일 감사의견코드  자산총계(요약)  \
14469  (주)지케이파워  54020.0  2001/12   4.0  2010/04/03     UQ   23774.0   
14470  (주)지케이파워  54020.0  2002/12   4.0  2010/04/03     UQ   32779.0   
14471  (주)지케이파워  54020.0  2003/12   4.0  2010/04/03     UQ   21193.0   
14472  (주)지케이파워  54020.0  2004/12   4.0  2010/04/03     UQ   12669.0   
14473  (주)지케이파워  54020.0  2005/12   4.0  2010/04/03     UQ   10098.0   
14474  (주)지케이파워  54020.0  2006/12   4.0  2010/04/03     UQ    9923.0   
14475  (주)지케이파워  54020.0  2007/12   4.0  2010/04/03     UQ    8611.0   
14476  (주)지케이파워  54020.0  2008/12   4.0  2010/04/03     UQ   23590.0   

       유동자산(요약)  당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  \
14469   15963.0    9485.0          2031.0  ...             NaN        NaN   
14470   14046.0    8254.0          3281.0  ...             NaN        NaN   
14471    8242.0    5079.0          1966.0  ...             NaN        NaN   
14472    4478.0    3210.0           177.0  ...             NaN        NaN   
14473    4202.0    2169.0           758.0  ...             NaN        NaN   
14474    3973.0    2704.0           507.0  ...             NaN        NaN   
14475    3311.0    2994.0           127.0  ...         -257.82        0.0   
14476   19464.0   19121.0            17.0  ...         -190.35        NaN   

          년_x        key   시간  회사명_y  종목코드  공시제목  제출인  년_y  
14469  2002.0  540202002  NaN    NaN   NaN   NaN  NaN  NaN  
14470  2003.0  540202003  NaN    NaN   NaN   NaN  NaN  NaN  
14471  2004.0  540202004  NaN    NaN   NaN   NaN  NaN  NaN  
14472  2005.0  540202005  NaN    NaN   NaN   NaN  NaN  NaN  
14473  2006.0  540202006  NaN    NaN   NaN   NaN  NaN  NaN  
14474  2007.0  540202007  NaN    NaN   NaN   NaN  NaN  NaN  
14475  2008.0  540202008  NaN    NaN   NaN   NaN  NaN  NaN  
14476  2009.0  540202009  NaN    NaN   NaN   NaN  NaN  NaN  

[8 rows x 275 columns]

In [270]:
merged.loc[merged['종목코드'] == 54020.0]

회사명_x  거래소코드 회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  당좌자산(요약)  \
27369   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   

       현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  년_x        key  \
27369             NaN  ...             NaN        NaN  NaN  540202010   

                     시간  회사명_y     종목코드  공시제목    제출인   년_y  
27369  2010-03-23 14:29   GK파워  54020.0  부도발생  지케이파워  2010  

[1 rows x 275 columns]

In [271]:
merged.loc[merged['key'] == '540202009', '공시제목'] = '부도발생'

### 디보스 80140.0

In [272]:
merged.loc[merged['거래소코드'] == 80140.0]

회사명_x    거래소코드     회계년도  소속코드       상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
2242  (주)디보스  80140.0  2002/12   4.0  2010/02/02     UQ   12254.0    7505.0   
2243  (주)디보스  80140.0  2003/12   4.0  2010/02/02     UQ   22113.0   14942.0   
2244  (주)디보스  80140.0  2004/12   4.0  2010/02/02     UQ   39390.0   28852.0   
2245  (주)디보스  80140.0  2005/12   4.0  2010/02/02     UQ   61574.0   40417.0   
2246  (주)디보스  80140.0  2006/12   4.0  2010/02/02     UQ   74910.0   49939.0   
2247  (주)디보스  80140.0  2007/12   4.0  2010/02/02     UQ   85008.0   56026.0   
2248  (주)디보스  80140.0  2008/12   4.0  2010/02/02     UQ   41196.0   11050.0   
2249  (주)디보스  80140.0  2008/12   4.0  2010/02/02     UQ   41196.0   11050.0   
2250  (주)디보스  80140.0  2008/12   4.0  2010/02/02     UQ   41196.0   11050.0   
2251  (주)디보스  80140.0  2008/12   4.0  2010/02/02     UQ   41196.0   11050.0   
2252  (주)디보스  80140.0  2008/12   4.0  2010/02/02     UQ   41196.0   11050.0   

      당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA     년_x  \
2242    3407.0          1699.0  ...             NaN        NaN  2003.0   
2243    8272.0           544.0  ...             NaN        NaN  2004.0   
2244   21590.0           277.0  ...             NaN        NaN  2005.0   
2245   20690.0            78.0  ...             NaN        NaN  2006.0   
2246   27833.0          3809.0  ...             NaN        NaN  2007.0   
2247   34775.0          7846.0  ...         -136.05        0.0  2008.0   
2248    4103.0            45.0  ...         -321.99        NaN  2009.0   
2249    4103.0            45.0  ...         -321.99        NaN  2009.0   
2250    4103.0            45.0  ...         -321.99        NaN  2009.0   
2251    4103.0            45.0  ...         -321.99        NaN  2009.0   
2252    4103.0            45.0  ...         -321.99        NaN  2009.0   

            key                시간  회사명_y     종목코드             공시제목  제출인   년_y  
2242  801402003               NaN    NaN      NaN              NaN  NaN   NaN  
2243  801402004               NaN    NaN      NaN              NaN  NaN   NaN  
2244  801402005               NaN    NaN      NaN              NaN  NaN   NaN  
2245  801402006               NaN    NaN      NaN              NaN  NaN   NaN  
2246  801402007               NaN    NaN      NaN              NaN  NaN   NaN  
2247  801402008               NaN    NaN      NaN              NaN  NaN   NaN  
2248  801402009  2009-08-11 17:24    디보스  80140.0     [정정]회생절차개시결정  디보스  2009  
2249  801402009  2009-07-21 16:44    디보스  80140.0  [정정]회생절차개시결정[정]  디보스  2009  
2250  801402009  2009-06-17 15:12    디보스  80140.0  [정정]회생절차개시결정[정]  디보스  2009  
2251  801402009  2009-04-21 15:07    디보스  80140.0      회생절차개시결정[정]  디보스  2009  
2252  801402009  2009-04-07 17:55    디보스  80140.0         회생절차개시신청  디보스  2009  

[11 rows x 275 columns]

In [273]:
merged.loc[merged['종목코드'] == 80140.0]

회사명_x    거래소코드     회계년도  소속코드       상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
2248   (주)디보스  80140.0  2008/12   4.0  2010/02/02     UQ   41196.0   11050.0   
2249   (주)디보스  80140.0  2008/12   4.0  2010/02/02     UQ   41196.0   11050.0   
2250   (주)디보스  80140.0  2008/12   4.0  2010/02/02     UQ   41196.0   11050.0   
2251   (주)디보스  80140.0  2008/12   4.0  2010/02/02     UQ   41196.0   11050.0   
2252   (주)디보스  80140.0  2008/12   4.0  2010/02/02     UQ   41196.0   11050.0   
27370     NaN      NaN      NaN   NaN         NaN    NaN       NaN       NaN   

       당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA     년_x  \
2248     4103.0            45.0  ...         -321.99        NaN  2009.0   
2249     4103.0            45.0  ...         -321.99        NaN  2009.0   
2250     4103.0            45.0  ...         -321.99        NaN  2009.0   
2251     4103.0            45.0  ...         -321.99        NaN  2009.0   
2252     4103.0            45.0  ...         -321.99        NaN  2009.0   
27370       NaN             NaN  ...             NaN        NaN     NaN   

             key                시간  회사명_y     종목코드             공시제목  제출인   년_y  
2248   801402009  2009-08-11 17:24    디보스  80140.0     [정정]회생절차개시결정  디보스  2009  
2249   801402009  2009-07-21 16:44    디보스  80140.0  [정정]회생절차개시결정[정]  디보스  2009  
2250   801402009  2009-06-17 15:12    디보스  80140.0  [정정]회생절차개시결정[정]  디보스  2009  
2251   801402009  2009-04-21 15:07    디보스  80140.0      회생절차개시결정[정]  디보스  2009  
2252   801402009  2009-04-07 17:55    디보스  80140.0         회생절차개시신청  디보스  2009  
27370  801402010  2010-01-26 14:34    디보스  80140.0        회생절차 폐지결정  디보스  2010  

[6 rows x 275 columns]

In [274]:
merged.loc[merged['key'] == '801402009', '공시제목']='회생절차 폐지결정'

### 평안물산 37240.0

In [275]:
merged.loc[merged['거래소코드'] == 37240.0]

회사명_x    거래소코드     회계년도  소속코드       상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
26333  평안물산(주)  37240.0  2000/12   4.0  2012/06/01     UQ   24759.0   17714.0   
26334  평안물산(주)  37240.0  2001/12   4.0  2012/06/01     UQ   48056.0   32116.0   
26335  평안물산(주)  37240.0  2002/12   4.0  2012/06/01     UQ   44564.0   27632.0   
26336  평안물산(주)  37240.0  2003/12   4.0  2012/06/01     UQ   32601.0   17553.0   
26337  평안물산(주)  37240.0  2004/12   4.0  2012/06/01     UQ   24300.0   13351.0   
26338  평안물산(주)  37240.0  2005/12   4.0  2012/06/01     UQ   17459.0   10569.0   
26339  평안물산(주)  37240.0  2006/12   4.0  2012/06/01     UQ   27098.0   16208.0   
26340  평안물산(주)  37240.0  2007/12   4.0  2012/06/01     UQ   48249.0   13399.0   
26341  평안물산(주)  37240.0  2008/12   4.0  2012/06/01     UQ   38425.0    8981.0   
26342  평안물산(주)  37240.0  2009/12   4.0  2012/06/01     UQ   21776.0    6177.0   
26343  평안물산(주)  37240.0  2010/12   4.0  2012/06/01     UQ   20419.0    7061.0   

       당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA     년_x  \
26333   15759.0          3316.0  ...             NaN        NaN  2001.0   
26334   28217.0         11055.0  ...             NaN        NaN  2002.0   
26335   24048.0          5945.0  ...             NaN        NaN  2003.0   
26336   14699.0          3084.0  ...             NaN        NaN  2004.0   
26337    9905.0          1712.0  ...             NaN        NaN  2005.0   
26338    8315.0          1475.0  ...             NaN        NaN  2006.0   
26339   15432.0         10401.0  ...             NaN        NaN  2007.0   
26340   12769.0          1745.0  ...         -217.00        0.0  2008.0   
26341    8524.0          1179.0  ...         -347.31        NaN  2009.0   
26342    6082.0          1967.0  ...          -62.87        NaN  2010.0   
26343    7023.0          1868.0  ...         -410.37        NaN  2011.0   

             key   시간  회사명_y  종목코드  공시제목  제출인  년_y  
26333  372402001  NaN    NaN   NaN   NaN  NaN  NaN  
26334  372402002  NaN    NaN   NaN   NaN  NaN  NaN  
26335  372402003  NaN    NaN   NaN   NaN  NaN  NaN  
26336  372402004  NaN    NaN   NaN   NaN  NaN  NaN  
26337  372402005  NaN    NaN   NaN   NaN  NaN  NaN  
26338  372402006  NaN    NaN   NaN   NaN  NaN  NaN  
26339  372402007  NaN    NaN   NaN   NaN  NaN  NaN  
26340  372402008  NaN    NaN   NaN   NaN  NaN  NaN  
26341  372402009  NaN    NaN   NaN   NaN  NaN  NaN  
26342  372402010  NaN    NaN   NaN   NaN  NaN  NaN  
26343  372402011  NaN    NaN   NaN   NaN  NaN  NaN  

[11 rows x 275 columns]

In [276]:
merged.loc[merged['종목코드'] == 37240.0]

회사명_x  거래소코드 회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  당좌자산(요약)  \
27371   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   

       현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  년_x        key  \
27371             NaN  ...             NaN        NaN  NaN  372402012   

                     시간  회사명_y     종목코드                          공시제목   제출인  \
27371  2012-03-15 19:32   평안물산  37240.0  내부결산시점 관리종목 지정 또는 상장폐지 사유 발생  평안물산   

        년_y  
27371  2012  

[1 rows x 275 columns]

In [277]:
merged.loc[merged['key'] == '372402011', '공시제목'] = '내부결산시점 관리종목 지정 또는 상장폐지 사유 발생'

### 에이프로테크놀로지 45470.0

In [278]:
merged.loc[merged['거래소코드'] == 45470.0]

회사명_x    거래소코드     회계년도  소속코드       상장폐지일 감사의견코드  자산총계(요약)  \
9547  (주)에이프로테크놀로지  45470.0  2000/12   4.0  2012/04/24     UQ    8491.0   
9548  (주)에이프로테크놀로지  45470.0  2001/12   4.0  2012/04/24     UQ   16676.0   
9549  (주)에이프로테크놀로지  45470.0  2002/12   4.0  2012/04/24     UQ   15814.0   
9550  (주)에이프로테크놀로지  45470.0  2003/12   4.0  2012/04/24     UQ   17830.0   
9551  (주)에이프로테크놀로지  45470.0  2004/12   4.0  2012/04/24     UQ   19749.0   
9552  (주)에이프로테크놀로지  45470.0  2005/12   4.0  2012/04/24     UQ   25537.0   
9553  (주)에이프로테크놀로지  45470.0  2006/12   4.0  2012/04/24     UQ   56938.0   
9554  (주)에이프로테크놀로지  45470.0  2007/12   4.0  2012/04/24     UQ   18484.0   
9555  (주)에이프로테크놀로지  45470.0  2008/12   4.0  2012/04/24     UQ   16201.0   
9556  (주)에이프로테크놀로지  45470.0  2009/12   4.0  2012/04/24     UQ   42009.0   
9557  (주)에이프로테크놀로지  45470.0  2010/12   4.0  2012/04/24     UQ   51411.0   

      유동자산(요약)  당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  \
9547    5988.0    5473.0           116.0  ...             NaN        NaN   
9548   11116.0   10570.0           822.0  ...             NaN        NaN   
9549   11017.0   10270.0           226.0  ...             NaN        NaN   
9550   10329.0    9763.0           749.0  ...             NaN        NaN   
9551    8032.0    7029.0           126.0  ...             NaN        NaN   
9552   15367.0   14761.0           518.0  ...             NaN        NaN   
9553   36080.0   36070.0            27.0  ...             NaN        NaN   
9554    5836.0    5751.0            24.0  ...         -155.28       0.00   
9555    3047.0    3001.0           545.0  ...         -195.96        NaN   
9556   19975.0   14589.0            36.0  ...           18.50      16.17   
9557   23036.0   16811.0           496.0  ...           16.75      15.08   

         년_x        key   시간  회사명_y  종목코드  공시제목  제출인  년_y  
9547  2001.0  454702001  NaN    NaN   NaN   NaN  NaN  NaN  
9548  2002.0  454702002  NaN    NaN   NaN   NaN  NaN  NaN  
9549  2003.0  454702003  NaN    NaN   NaN   NaN  NaN  NaN  
9550  2004.0  454702004  NaN    NaN   NaN   NaN  NaN  NaN  
9551  2005.0  454702005  NaN    NaN   NaN   NaN  NaN  NaN  
9552  2006.0  454702006  NaN    NaN   NaN   NaN  NaN  NaN  
9553  2007.0  454702007  NaN    NaN   NaN   NaN  NaN  NaN  
9554  2008.0  454702008  NaN    NaN   NaN   NaN  NaN  NaN  
9555  2009.0  454702009  NaN    NaN   NaN   NaN  NaN  NaN  
9556  2010.0  454702010  NaN    NaN   NaN   NaN  NaN  NaN  
9557  2011.0  454702011  NaN    NaN   NaN   NaN  NaN  NaN  

[11 rows x 275 columns]

In [279]:
merged.loc[merged['종목코드'] == 45470.0]

회사명_x  거래소코드 회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  당좌자산(요약)  \
27372   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   

       현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  년_x        key  \
27372             NaN  ...             NaN        NaN  NaN  454702012   

                     시간      회사명_y     종목코드                          공시제목  \
27372  2012-03-15 18:24  에이프로테크놀로지  45470.0  내부결산시점 관리종목 지정 또는 상장폐지 사유 발생   

             제출인   년_y  
27372  에이프로테크놀로지  2012  

[1 rows x 275 columns]

In [280]:
merged.loc[merged['key'] == '454702011', '공시제목'] = '내부결산시점 관리종목 지정 또는 상장폐지 사유 발생'

### 우양에이치씨 101970.0

In [281]:
merged.loc[merged['거래소코드'] == 101970.0]

회사명_x     거래소코드     회계년도  소속코드       상장폐지일 감사의견코드  자산총계(요약)  \
24513  우양에이치씨(주)  101970.0  2003/12   4.0  2015/03/17     UQ   10168.0   
24514  우양에이치씨(주)  101970.0  2004/12   4.0  2015/03/17     UQ   24334.0   
24515  우양에이치씨(주)  101970.0  2005/12   4.0  2015/03/17     UQ   34892.0   
24516  우양에이치씨(주)  101970.0  2006/12   4.0  2015/03/17     UQ   66313.0   
24517  우양에이치씨(주)  101970.0  2007/12   4.0  2015/03/17     UQ   78402.0   
24518  우양에이치씨(주)  101970.0  2008/12   4.0  2015/03/17     UQ  131395.0   
24519  우양에이치씨(주)  101970.0  2009/12   4.0  2015/03/17     UQ  161973.0   
24520  우양에이치씨(주)  101970.0  2010/12   4.0  2015/03/17     UQ  210294.0   
24521  우양에이치씨(주)  101970.0  2011/12   4.0  2015/03/17     UQ  233181.0   
24522  우양에이치씨(주)  101970.0  2012/12   4.0  2015/03/17     UQ  316015.0   
24523  우양에이치씨(주)  101970.0  2013/12   4.0  2015/03/17     UQ  373356.0   

       유동자산(요약)  당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  \
24513    5048.0    4268.0           453.0  ...             NaN        NaN   
24514    7796.0    6731.0           772.0  ...             NaN        NaN   
24515   13034.0   12722.0           177.0  ...             NaN        NaN   
24516   30264.0   25145.0           143.0  ...             NaN        NaN   
24517   35089.0   31054.0           443.0  ...         1576.79       2.53   
24518   77255.0   69711.0          1422.0  ...         1319.58       5.03   
24519  100978.0   97740.0         11569.0  ...         2085.08       1.95   
24520  133253.0  125697.0          1470.0  ...         1512.36       4.57   
24521  153383.0  143876.0          4510.0  ...         1611.19       3.29   
24522  193413.0  182311.0          6934.0  ...         2536.23       7.25   
24523  216090.0  206137.0          1693.0  ...         1569.33      10.49   

          년_x         key   시간  회사명_y  종목코드  공시제목  제출인  년_y  
24513  2004.0  1019702004  NaN    NaN   NaN   NaN  NaN  NaN  
24514  2005.0  1019702005  NaN    NaN   NaN   NaN  NaN  NaN  
24515  2006.0  1019702006  NaN    NaN   NaN   NaN  NaN  NaN  
24516  2007.0  1019702007  NaN    NaN   NaN   NaN  NaN  NaN  
24517  2008.0  1019702008  NaN    NaN   NaN   NaN  NaN  NaN  
24518  2009.0  1019702009  NaN    NaN   NaN   NaN  NaN  NaN  
24519  2010.0  1019702010  NaN    NaN   NaN   NaN  NaN  NaN  
24520  2011.0  1019702011  NaN    NaN   NaN   NaN  NaN  NaN  
24521  2012.0  1019702012  NaN    NaN   NaN   NaN  NaN  NaN  
24522  2013.0  1019702013  NaN    NaN   NaN   NaN  NaN  NaN  
24523  2014.0  1019702014  NaN    NaN   NaN   NaN  NaN  NaN  

[11 rows x 275 columns]

In [282]:
merged.loc[merged['종목코드'] == 101970.0]

회사명_x  거래소코드 회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  당좌자산(요약)  \
27373   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27374   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   

       현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  년_x         key  \
27373             NaN  ...             NaN        NaN  NaN  1019702015   
27374             NaN  ...             NaN        NaN  NaN  1019702015   

                     시간   회사명_y      종목코드      공시제목     제출인   년_y  
27373  2015-03-04 16:49  우양에이치씨  101970.0      부도발생  우양에이치씨  2015  
27374  2015-03-02 18:15  우양에이치씨  101970.0  회생절차개시신청  우양에이치씨  2015  

[2 rows x 275 columns]

In [283]:
merged.loc[merged['key'] == '1019702014', '공시제목'] = '부도발생'

### 럭슬 33600.0

In [284]:
merged.loc[merged['거래소코드'] == 33600.0]

회사명_x    거래소코드     회계년도  소속코드       상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
21173  럭슬(주)  33600.0  2000/12   4.0  2021/08/11     UQ   39379.0   20589.0   
21174  럭슬(주)  33600.0  2001/12   4.0  2021/08/11     UQ   42842.0   18792.0   
21175  럭슬(주)  33600.0  2002/12   4.0  2021/08/11     UQ   50805.0   24888.0   
21176  럭슬(주)  33600.0  2003/12   4.0  2021/08/11     UQ   49951.0   20707.0   
21177  럭슬(주)  33600.0  2004/12   4.0  2021/08/11     UQ   46989.0   14891.0   
21178  럭슬(주)  33600.0  2005/12   4.0  2021/08/11     UQ   58238.0   16699.0   
21179  럭슬(주)  33600.0  2006/12   4.0  2021/08/11     UQ   56398.0   15533.0   
21180  럭슬(주)  33600.0  2007/12   4.0  2021/08/11     UQ   54904.0   18249.0   
21181  럭슬(주)  33600.0  2008/12   4.0  2021/08/11     UQ   88812.0   26849.0   
21182  럭슬(주)  33600.0  2009/12   4.0  2021/08/11     UQ   91332.0   27214.0   
21183  럭슬(주)  33600.0  2010/12   4.0  2021/08/11     UQ   89670.0   28159.0   
21184  럭슬(주)  33600.0  2011/12   4.0  2021/08/11     UQ   84482.0   16043.0   
21185  럭슬(주)  33600.0  2012/12   4.0  2021/08/11     UQ   77726.0   10945.0   
21186  럭슬(주)  33600.0  2013/12   4.0  2021/08/11     UQ   75999.0   10830.0   
21187  럭슬(주)  33600.0  2014/12   4.0  2021/08/11     UQ   70350.0   13101.0   
21188  럭슬(주)  33600.0  2015/12   4.0  2021/08/11     UQ   60597.0    8575.0   
21189  럭슬(주)  33600.0  2016/12   4.0  2021/08/11     UQ   54897.0    7657.0   
21190  럭슬(주)  33600.0  2017/12   4.0  2021/08/11     UQ   54619.0    6814.0   
21191  럭슬(주)  33600.0  2018/12   4.0  2021/08/11     UQ   66145.0   23065.0   

       당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA     년_x  \
21173   20383.0          4228.0  ...             NaN        NaN  2001.0   
21174   18163.0          7707.0  ...             NaN        NaN  2002.0   
21175   23638.0          7598.0  ...             NaN        NaN  2003.0   
21176   18521.0          8826.0  ...             NaN        NaN  2004.0   
21177   13739.0          5160.0  ...             NaN        NaN  2005.0   
21178   15518.0          3626.0  ...             NaN        NaN  2006.0   
21179   13996.0          3704.0  ...             NaN        NaN  2007.0   
21180   17188.0          5363.0  ...          412.11       6.43  2008.0   
21181   25896.0          6730.0  ...          327.40       6.06  2009.0   
21182   25808.0          2950.0  ...          135.96      27.21  2010.0   
21183   27004.0          6542.0  ...           28.49     106.10  2011.0   
21184   14276.0          2613.0  ...          222.97      14.88  2012.0   
21185   10085.0          1376.0  ...           19.36     182.09  2013.0   
21186    9300.0            88.0  ...           25.54     146.60  2014.0   
21187    9689.0           742.0  ...          322.58      10.90  2015.0   
21188    5950.0          1691.0  ...          -78.39       0.00  2016.0   
21189    5934.0          1414.0  ...         -255.88       0.00  2017.0   
21190    6284.0            70.0  ...         -256.71       0.00  2018.0   
21191   22673.0           431.0  ...         -336.67       0.00  2019.0   

             key   시간  회사명_y  종목코드  공시제목  제출인  년_y  
21173  336002001  NaN    NaN   NaN   NaN  NaN  NaN  
21174  336002002  NaN    NaN   NaN   NaN  NaN  NaN  
21175  336002003  NaN    NaN   NaN   NaN  NaN  NaN  
21176  336002004  NaN    NaN   NaN   NaN  NaN  NaN  
21177  336002005  NaN    NaN   NaN   NaN  NaN  NaN  
21178  336002006  NaN    NaN   NaN   NaN  NaN  NaN  
21179  336002007  NaN    NaN   NaN   NaN  NaN  NaN  
21180  336002008  NaN    NaN   NaN   NaN  NaN  NaN  
21181  336002009  NaN    NaN   NaN   NaN  NaN  NaN  
21182  336002010  NaN    NaN   NaN   NaN  NaN  NaN  
21183  336002011  NaN    NaN   NaN   NaN  NaN  NaN  
21184  336002012  NaN    NaN   NaN   NaN  NaN  NaN  
21185  336002013  NaN    NaN   NaN   NaN  NaN  NaN  
21186  336002014  NaN    NaN   NaN   NaN  NaN  NaN  
21187  336002015  NaN    NaN   NaN   NaN  NaN  NaN  
21188  336002016  NaN    NaN   NaN   NaN  NaN  NaN  
21189  336002017  NaN   

In [285]:
merged.loc[merged['종목코드'] == 33600.0]

회사명_x  거래소코드 회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  당좌자산(요약)  \
27375   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27376   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   

       현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  년_x        key  \
27375             NaN  ...             NaN        NaN  NaN  336002020   
27376             NaN  ...             NaN        NaN  NaN  336002020   

                     시간  회사명_y     종목코드          공시제목  제출인   년_y  
27375  2020-11-17 16:01     럭슬  33600.0  [정정]회생절차개시신청   럭슬  2020  
27376  2020-09-02 15:40     럭슬  33600.0   회생절차개시신청[정]   럭슬  2020  

[2 rows x 275 columns]

In [286]:
merged.loc[merged['key'] == '336002019', '공시제목']='[정정]회생절차개시신청'

### 이노와이즈 86250.0

In [287]:
merged.loc[merged['거래소코드'] == 86250.0]

회사명_x    거래소코드     회계년도  소속코드       상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
19275  (주)화신테크  86250.0  2000/12   4.0  2021/08/31     UQ   15068.0    6276.0   
19276  (주)화신테크  86250.0  2001/12   4.0  2021/08/31     UQ   14566.0    4417.0   
19277  (주)화신테크  86250.0  2002/12   4.0  2021/08/31     UQ   13941.0    3788.0   
19278  (주)화신테크  86250.0  2003/12   4.0  2021/08/31     UQ   16421.0    4539.0   
19279  (주)화신테크  86250.0  2004/12   4.0  2021/08/31     UQ   19357.0    5994.0   
19280  (주)화신테크  86250.0  2005/12   4.0  2021/08/31     UQ   26217.0    7021.0   
19281  (주)화신테크  86250.0  2006/12   4.0  2021/08/31     UQ   34097.0   14522.0   
19282  (주)화신테크  86250.0  2007/12   4.0  2021/08/31     UQ   33153.0   12018.0   
19283  (주)화신테크  86250.0  2008/12   4.0  2021/08/31     UQ   35176.0   11011.0   
19284  (주)화신테크  86250.0  2009/12   4.0  2021/08/31     UQ   37843.0    7507.0   
19285  (주)화신테크  86250.0  2010/12   4.0  2021/08/31     UQ   51019.0    9952.0   
19286  (주)화신테크  86250.0  2011/12   4.0  2021/08/31     UQ   57129.0   13786.0   
19287  (주)화신테크  86250.0  2012/12   4.0  2021/08/31     UQ   57850.0   15754.0   
19288  (주)화신테크  86250.0  2013/12   4.0  2021/08/31     UQ   68865.0   33138.0   
19289  (주)화신테크  86250.0  2014/12   4.0  2021/08/31     UQ   76066.0   21127.0   
19290  (주)화신테크  86250.0  2015/12   4.0  2021/08/31     UQ   81877.0   27462.0   
19291  (주)화신테크  86250.0  2016/12   4.0  2021/08/31     UQ   69811.0   35543.0   
19292  (주)화신테크  86250.0  2017/12   4.0  2021/08/31     UQ   66704.0   33481.0   
19293  (주)화신테크  86250.0  2018/12   4.0  2021/08/31     UQ   55260.0   19533.0   
19294  (주)화신테크  86250.0  2020/12   4.0  2021/08/31     DU   46883.0    8511.0   

       당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA     년_x  \
19275    6240.0           130.0  ...             NaN        NaN  2001.0   
19276    4412.0           126.0  ...             NaN        NaN  2002.0   
19277    3784.0            49.0  ...             NaN        NaN  2003.0   
19278    4536.0           325.0  ...             NaN        NaN  2004.0   
19279    5989.0          2179.0  ...             NaN        NaN  2005.0   
19280    7017.0           642.0  ...             NaN        NaN  2006.0   
19281   14518.0          1276.0  ...             NaN        NaN  2007.0   
19282   12014.0          3118.0  ...          -22.24       0.00  2008.0   
19283   10998.0           654.0  ...           70.27       1.09  2009.0   
19284    7499.0          1003.0  ...          116.57      14.67  2010.0   
19285    9944.0          1076.0  ...          129.34      18.53  2011.0   
19286   13774.0           322.0  ...          125.59      18.68  2012.0   
19287   15737.0           751.0  ...          153.02      18.65  2013.0   
19288   33121.0         14496.0  ...          254.04       7.91  2014.0   
19289   21105.0           137.0  ...          256.52      18.01  2015.0   
19290   27413.0          2355.0  ...          159.23      39.19  2016.0   
19291   35533.0          4351.0  ...          -42.82       0.00  2017.0   
19292   33476.0          2924.0  ...          140.69      29.71  2018.0   
19293   19526.0           171.0  ...         -283.03       0.00  2019.0   
19294    8510.0          3033.0  ...         -212.58       0.00  2021.0   

             key   시간  회사명_y  종목코드  공시제목  제출인  년_y  
19275  862502001  NaN    NaN   NaN   NaN  NaN  NaN  
19276  862502002  NaN    NaN   NaN   NaN  NaN  NaN  
19277  862502003  NaN    NaN   NaN   NaN  NaN  NaN  
19278  862502004  NaN    NaN   NaN   NaN  NaN  NaN  
19279  862502005  NaN    NaN   NaN   NaN  NaN  NaN  
19280  862502006  NaN    NaN   NaN   NaN  NaN  NaN  
19281  862502007  NaN    NaN   NaN   NaN  NaN  NaN  
19282  862502008  NaN    NaN   NaN   NaN  NaN  NaN  
19283  862502009  NaN    NaN   NaN   NaN  NaN  NaN  
19284  862502010  NaN    NaN   NaN   NaN  NaN  NaN  
19285  862502011  NaN    NaN   NaN   NaN  NaN  NaN  
19286  862502012  NaN    NaN   NaN   NaN  NaN  NaN  
19287  862502013  NaN    NaN   NaN   NaN  

In [288]:
merged.loc[merged['종목코드'] == 86250.0]

회사명_x  거래소코드 회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  당좌자산(요약)  \
27377   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   
27378   NaN    NaN  NaN   NaN   NaN    NaN       NaN       NaN       NaN   

       현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA  년_x        key  \
27377             NaN  ...             NaN        NaN  NaN  862502020   
27378             NaN  ...             NaN        NaN  NaN  862502020   

                     시간  회사명_y     종목코드      공시제목   제출인   년_y  
27377  2020-07-28 14:54  이노와이즈  86250.0  회생절차개시결정  화신테크  2020  
27378  2020-05-08 15:03  이노와이즈  86250.0  회생절차개시신청  화신테크  2020  

[2 rows x 275 columns]

In [289]:
merged.loc[merged['key'] == '862502021', '공시제목'] = '회생절차개시신청'

In [290]:
#저장 
#merged.to_csv('재무변수_부도사유_verSH.csv')

# 하다가말았다

In [291]:
merged.head(25)

회사명_x    거래소코드     회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
0   (주)CMG제약  58820.0  2000/12   5.0   NaN     UQ   28990.0   21169.0   
1   (주)CMG제약  58820.0  2001/12   5.0   NaN     UQ   20908.0   16359.0   
2   (주)CMG제약  58820.0  2002/12   5.0   NaN     UQ   15401.0    9880.0   
3   (주)CMG제약  58820.0  2003/12   5.0   NaN     UQ   11063.0    8534.0   
4   (주)CMG제약  58820.0  2004/12   5.0   NaN     UQ    5179.0    3893.0   
5   (주)CMG제약  58820.0  2005/12   5.0   NaN     UQ    8280.0    3449.0   
6   (주)CMG제약  58820.0  2006/12   5.0   NaN     UQ   10030.0    6897.0   
7   (주)CMG제약  58820.0  2007/12   5.0   NaN     UQ   22074.0    8952.0   
8   (주)CMG제약  58820.0  2008/12   5.0   NaN     UQ   34557.0   16725.0   
9   (주)CMG제약  58820.0  2009/12   5.0   NaN     UQ   22836.0    9827.0   
10  (주)CMG제약  58820.0  2010/12   5.0   NaN     UQ   24128.0   11604.0   
11  (주)CMG제약  58820.0  2011/12   5.0   NaN     UQ   27549.0   15265.0   
12  (주)CMG제약  58820.0  2012/12   5.0   NaN     UQ   56989.0   47073.0   
13  (주)CMG제약  58820.0  2013/12   5.0   NaN     UQ   55962.0   38259.0   
14  (주)CMG제약  58820.0  2014/12   5.0   NaN     UQ   58127.0   28360.0   
15  (주)CMG제약  58820.0  2015/12   5.0   NaN     UQ   56592.0   26331.0   
16  (주)CMG제약  58820.0  2016/12   5.0   NaN     UQ  110980.0   78772.0   
17  (주)CMG제약  58820.0  2017/12   5.0   NaN     UQ  109568.0   81227.0   
18  (주)CMG제약  58820.0  2018/12   5.0   NaN     UQ  114380.0   81370.0   
19  (주)CMG제약  58820.0  2019/12   5.0   NaN     UQ  192243.0  150584.0   
20  (주)CMG제약  58820.0  2020/12   5.0   NaN     UQ  195356.0  145981.0   
21   (주)ES큐브  50120.0  2001/06   5.0   NaN     UQ    7040.0    3825.0   
22   (주)ES큐브  50120.0  2002/06   5.0   NaN     UQ    9447.0    5384.0   
23   (주)ES큐브  50120.0  2003/06   5.0   NaN     UQ    9538.0    5792.0   
24   (주)ES큐브  50120.0  2004/06   5.0   NaN     UQ   15645.0   11859.0   

    당좌자산(요약)  현금 및 현금성자산(요약)  ...  EBITDA/평균발행주식수  EV/EBITDA     년_x  \
0    10541.0          4330.0  ...             NaN        NaN  2001.0   
1     2307.0          1829.0  ...             NaN        NaN  2002.0   
2     1436.0           355.0  ...             NaN        NaN  2003.0   
3     1083.0             2.0  ...             NaN        NaN  2004.0   
4      445.0            11.0  ...             NaN        NaN  2005.0   
5     3226.0           609.0  ...             NaN        NaN  2006.0   
6     6897.0          2850.0  ...             NaN        NaN  2007.0   
7     8638.0          2714.0  ...         -104.44       0.00  2008.0   
8    15015.0          6233.0  ...         -221.19        NaN  2009.0   
9     7398.0          1063.0  ...         -443.98        NaN  2010.0   
10    8721.0          2447.0  ...         -243.34        NaN  2011.0   
11   12522.0          1152.0  ...           46.75      18.52  2012.0   
12   44118.0          4673.0  ...          -54.30       0.00  2013.0   
13   33640.0         21705.0  ...           22.28      31.32  2014.0   
14   23447.0          8827.0  ...           22.06      37.53  2015.0   
15   20875.0          2566.0  ...           -7.71       0.00  2016.0   
16   72378.0          2149.0  ...           41.96      89.66  2017.0   
17   73323.0          3799.0  ...           31.37     197.94  2018.0   
18   72798.0         13464.0  ...           40.54     101.42  2019.0   
19  141535.0         18571.0  ...           43.25     121.46  2020.0   
20  130934.0          8044.0  ...           30.66     186.77  2021.0   
21    3713.0           509.0  ...             NaN        NaN  2002.0   
22    5279.0          1671.0  ...             NaN        NaN  2003.0   
23    5725.0           256.0  ...             NaN        NaN  2004.0   
24   11767.0          3992.0  ...             NaN        NaN  2005.0   

          key   시간  회사명_y  종목코드  공시제목  제출인  년_y  
0   588202001  NaN    NaN   NaN   NaN  NaN  NaN  
1   588202002  NaN    NaN   NaN   NaN  NaN  NaN  
2   588202003  NaN    NaN   NaN   NaN  NaN  NaN  
3   588202004  NaN    NaN   NaN   N

In [292]:
merged.isna().sum()

회사명_x       22
거래소코드       22
회계년도        22
소속코드        22
상장폐지일    21943
         ...  
회사명_y    26985
종목코드     26985
공시제목     26976
제출인      26993
년_y      26985
Length: 275, dtype: int64

In [293]:
df = merged[merged['회사명_x'].notna()]

In [294]:
df.drop(columns=['시간','회사명_y','종목코드', '제출인', '년_y'],inplace=True)

C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [295]:
df.rename(columns = {'회사명_x' : '회사명'}, inplace = True)
df.rename(columns = {'년_x' : '년'}, inplace = True)
df

C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


회사명    거래소코드     회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
0      (주)CMG제약  58820.0  2000/12   5.0   NaN     UQ   28990.0   21169.0   
1      (주)CMG제약  58820.0  2001/12   5.0   NaN     UQ   20908.0   16359.0   
2      (주)CMG제약  58820.0  2002/12   5.0   NaN     UQ   15401.0    9880.0   
3      (주)CMG제약  58820.0  2003/12   5.0   NaN     UQ   11063.0    8534.0   
4      (주)CMG제약  58820.0  2004/12   5.0   NaN     UQ    5179.0    3893.0   
...         ...      ...      ...   ...   ...    ...       ...       ...   
27352   흥구석유(주)  24060.0  2016/12   5.0   NaN     UQ   79137.0   14794.0   
27353   흥구석유(주)  24060.0  2017/12   5.0   NaN     UQ   79912.0   15880.0   
27354   흥구석유(주)  24060.0  2018/12   5.0   NaN     UQ   75206.0   12515.0   
27355   흥구석유(주)  24060.0  2019/12   5.0   NaN     UQ   83661.0   22620.0   
27356   흥구석유(주)  24060.0  2020/12   5.0   NaN     UQ   83721.0   27688.0   

       당좌자산(요약)  현금 및 현금성자산(요약)  ...  PSR(Price sales ratio)(최저)   기업가치(EV)  \
0       10541.0          4330.0  ...                         NaN        NaN   
1        2307.0          1829.0  ...                         NaN        NaN   
2        1436.0           355.0  ...                         NaN        NaN   
3        1083.0             2.0  ...                         NaN        NaN   
4         445.0            11.0  ...                         NaN        NaN   
...         ...             ...  ...                         ...        ...   
27352   12274.0          1440.0  ...                        0.28   55934.79   
27353   13124.0          1588.0  ...                        0.24   46036.63   
27354   11029.0          4017.0  ...                        0.24   36557.57   
27355   19701.0          2318.0  ...                        0.25   78081.78   
27356   25313.0          1413.0  ...                        0.40  107308.51   

        EBITDA  EBITDA/매출액  EBITDA/금융비용  EBITDA/평균발행주식수  EV/EBITDA       년  \
0          NaN         NaN          NaN             NaN        NaN  2001.0   
1          NaN         NaN          NaN             NaN        NaN  2002.0   
2          NaN         NaN          NaN             NaN        NaN  2003.0   
3          NaN         NaN          NaN             NaN        NaN  2004.0   
4          NaN         NaN          NaN             NaN        NaN  2005.0   
...        ...         ...          ...             ...        ...     ...   
27352  1348.52        0.94        10.71           89.90      41.48  2017.0   
27353  1147.56        0.74         9.02           76.50      40.12  2018.0   
27354  1451.79        0.87        16.83           96.79      25.18  2019.0   
27355  1009.25        0.67       507.93           67.28      77.37  2020.0   
27356    16.31        0.01         0.00            1.09    6579.47  2021.0   

             key  공시제목  
0      588202001   NaN  
1      588202002   NaN  
2      588202003   NaN  
3      588202004   NaN  
4      588202005   NaN  
...          ...   ...  
27352  240602017   NaN  
27353  240602018   NaN  
27354  240602019   NaN  
27355  240602020   NaN  
27356  240602021   NaN  

[27357 rows x 270 columns]

In [296]:
df.to_csv('임시.csv')

In [297]:
df.loc[(df['소속코드'] == 4) & 
((df['감사의견코드'] == 'DS') | (df['감사의견코드'] == 'DU') | (df['감사의견코드'] == 'AG') | (df['감사의견코드'] == 'DI') | (df['감사의견코드'] == 'QS')
| (df['공시제목'].notna())), '부도'] = 0

C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py:1684: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = infer_fill_value(value)
C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


In [298]:
df['부도']=df['부도'].fillna(1)

C:\Users\user\AppData\Local\Temp/ipykernel_6632/1167929933.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['부도']=df['부도'].fillna(1)


In [299]:
df

회사명    거래소코드     회계년도  소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
0      (주)CMG제약  58820.0  2000/12   5.0   NaN     UQ   28990.0   21169.0   
1      (주)CMG제약  58820.0  2001/12   5.0   NaN     UQ   20908.0   16359.0   
2      (주)CMG제약  58820.0  2002/12   5.0   NaN     UQ   15401.0    9880.0   
3      (주)CMG제약  58820.0  2003/12   5.0   NaN     UQ   11063.0    8534.0   
4      (주)CMG제약  58820.0  2004/12   5.0   NaN     UQ    5179.0    3893.0   
...         ...      ...      ...   ...   ...    ...       ...       ...   
27352   흥구석유(주)  24060.0  2016/12   5.0   NaN     UQ   79137.0   14794.0   
27353   흥구석유(주)  24060.0  2017/12   5.0   NaN     UQ   79912.0   15880.0   
27354   흥구석유(주)  24060.0  2018/12   5.0   NaN     UQ   75206.0   12515.0   
27355   흥구석유(주)  24060.0  2019/12   5.0   NaN     UQ   83661.0   22620.0   
27356   흥구석유(주)  24060.0  2020/12   5.0   NaN     UQ   83721.0   27688.0   

       당좌자산(요약)  현금 및 현금성자산(요약)  ...   기업가치(EV)   EBITDA  EBITDA/매출액  \
0       10541.0          4330.0  ...        NaN      NaN         NaN   
1        2307.0          1829.0  ...        NaN      NaN         NaN   
2        1436.0           355.0  ...        NaN      NaN         NaN   
3        1083.0             2.0  ...        NaN      NaN         NaN   
4         445.0            11.0  ...        NaN      NaN         NaN   
...         ...             ...  ...        ...      ...         ...   
27352   12274.0          1440.0  ...   55934.79  1348.52        0.94   
27353   13124.0          1588.0  ...   46036.63  1147.56        0.74   
27354   11029.0          4017.0  ...   36557.57  1451.79        0.87   
27355   19701.0          2318.0  ...   78081.78  1009.25        0.67   
27356   25313.0          1413.0  ...  107308.51    16.31        0.01   

       EBITDA/금융비용  EBITDA/평균발행주식수  EV/EBITDA       년        key  공시제목   부도  
0              NaN             NaN        NaN  2001.0  588202001   NaN  1.0  
1              NaN             NaN        NaN  2002.0  588202002   NaN  1.0  
2              NaN             NaN        NaN  2003.0  588202003   NaN  1.0  
3              NaN             NaN        NaN  2004.0  588202004   NaN  1.0  
4              NaN             NaN        NaN  2005.0  588202005   NaN  1.0  
...            ...             ...        ...     ...        ...   ...  ...  
27352        10.71           89.90      41.48  2017.0  240602017   NaN  1.0  
27353         9.02           76.50      40.12  2018.0  240602018   NaN  1.0  
27354        16.83           96.79      25.18  2019.0  240602019   NaN  1.0  
27355       507.93           67.28      77.37  2020.0  240602020   NaN  1.0  
27356         0.00            1.09    6579.47  2021.0  240602021   NaN  1.0  

[27357 rows x 271 columns]

In [300]:
df['부도'].value_counts()

1.0    26915
0.0      442
Name: 부도, dtype: int64

In [ ]:
df.to_csv('재무변수_부도사유_ver2SH.csv')

In [301]:
#df.to_csv('재무변수_부도사유_verSH1130.csv')