# 부도기업예측을 위한 재무변수 전처리<br>

1. 거래소번호 수 6자리 맞추기 -> 0으로 맞춰도 새로 CVS read시 0 다 누락되어 처리하지않기로 함 <br>
2. nan값 해결해야합니당 -> 결측치가 많은 칼럼은 중요도를 따진 후 feature selection 전 드랍 예정<br>
3. KIND에서 가져온 공시정보다 매칭되지 않은 13개 기업 공시제목 강제할당 처리 완 


In [30]:
del train, train_full, bankrupt, merged

NameError: name 'train' is not defined

In [31]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import plotly.express as px
import tqdm

In [32]:
train_full = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\코드_재무변수.csv', encoding='euc-kr')
train = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\코드_재무변수.csv', encoding='euc-kr', usecols = ['회사명','거래소코드','회계년도','소속코드','상장폐지일'])
#bankrupt = pd.read_csv(r'C:\Users\user\Desktop\code\부실기업\kind_bankrupt_df.csv', index_col=0)  ㅇ

In [33]:
#회계년도 추출
train['년'] = train['회계년도'].str[:4]
train_full['년'] = train_full['회계년도'].str[:4]

#회계년도+1 칼럼 생성 : 사업보고서 연도와 공시 데이터 연도 시점차이로 인해 +1
train['년+1'] = train['회계년도'].str[0:4].astype(int) + 1
train_full['년+1'] = train_full['회계년도'].str[0:4].astype(int) + 1

### KIND에서 추출한 상폐관련 공시 리스트 CSV화

In [6]:
d0002 = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\부도사유데이터\부도사유0002.csv')
d0305 = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\부도사유데이터\부도사유0305.csv')
d0608 = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\부도사유데이터\부도사유0608.csv')
d0911 = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\부도사유데이터\부도사유0911.csv')
d1214 = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\부도사유데이터\부도사유1214.csv')
d1517 = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\부도사유데이터\부도사유1517.csv')
d1820 = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Data\부도사유데이터\부도사유1820.csv')

In [15]:
bankrupt_df = pd.concat([d0002, d0305,d0608, d0911, d1214, d1517, d1820], axis=0).reset_index()
bankrupt_df.drop(columns=['index'], inplace=True)

In [25]:
bankrupt_df

시간     회사명    종목코드  \
0    2002-10-31 18:27    정산애강   22220   
1    2002-10-08 12:06   대호특수강   21040   
2    2002-05-21 18:16   에이치엘비   28300   
3    2002-04-17 17:42   에이치엘비   28300   
4    2001-12-26 14:58   대호특수강   21040   
..                ...     ...     ...   
389  2020-02-12 16:21  에스앤더블류  103230   
390  2020-02-11 17:02     파나진   46210   
391  2020-02-10 16:32     국순당   43650   
392  2020-02-10 16:24    유아이디   69330   
393  2020-02-07 17:14     이녹스   88390   

                                             공시제목     제출인  
0                                     부도발생및은행거래정지    정산애강  
1                                          은행거래재개   대호특수강  
2                                      회사정리절차종결결정   에이치엘비  
3                                      회사정리절차종결신청   에이치엘비  
4                                      회사정리절차개시결정   대호특수강  
..                                            ...     ...  
389                  내부결산시점 관리종목 지정 또는 상장폐지 사유 발생  에스앤더블류  
390                  내부결산시점 관리종목 지정 또는 상장폐지 사유 발생     파나진  
391               내부결산시점 관리종목 지정 또는 상장폐지 사유 발생[정]     국순당  
392                  내부결산시점 관리종목 지정 또는 상장폐지 사유 발생    유아이디  
393  내부결산시점 관리종목 지정 또는 상장폐지 사유 발생(자회사의 주요경영사항)[정]     이녹스  

[394 rows x 5 columns]

In [27]:
#저장
bankrupt_df.to_csv('kind_bankrupt_df.csv')

### bankrupt_df 파일 불러온 후 시간 슬라이싱

In [34]:
bankrupt = pd.read_csv(r'C:\Users\user\Desktop\code\부실기업\kind_bankrupt_df.csv', index_col=0)

In [35]:
#년도 추출
bankrupt['년'] = bankrupt['시간'].str[:4]

In [36]:
bankrupt.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 394 entries, 0 to 393
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   시간      394 non-null    object
 1   회사명     394 non-null    object
 2   종목코드    394 non-null    int64 
 3   공시제목    394 non-null    object
 4   제출인     386 non-null    object
 5   년       394 non-null    object
dtypes: int64(1), object(5)
memory usage: 21.5+ KB


In [ ]:
#dataset.loc[(dataset['occyp_type'] == 'Nan') & (dataset['DAYS_EMPLOYED'] == 0), 'occyp_type'] = 'jobless'

In [37]:
print(train.shape)
print(bankrupt.shape)

(27166, 7)
(394, 6)


In [101]:
27166+394

27560

### train, bankrupt merge위한 key 만들기 : 종목코드 + 년 

In [38]:
bankrupt['key'] = bankrupt['종목코드'].astype(str) +  bankrupt['년']

In [39]:
train['key'] = train['거래소코드'].astype(str) + train['년+1'].astype(str)
train_full['key'] = train_full['거래소코드'].astype(str) + train_full['년+1'].astype(str)

In [40]:
merged = pd.merge(train_full, bankrupt, on = 'key', how = 'outer')
# merged = pd.merge(train_full, bankrupt, on = 'key', how = 'outer')

In [41]:
merged = merged.fillna('임시')

In [42]:
merged[merged['회사명_x']=='임시']

회사명_x 거래소코드 회계년도 소속코드 상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약) 당좌자산(요약)  \
27357    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27358    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27359    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27360    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27361    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27362    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27363    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27364    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27365    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27366    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27367    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27368    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27369    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27370    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27371    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27372    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27373    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27374    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27375    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27376    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27377    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27378    임시    임시   임시   임시    임시     임시       임시       임시       임시   

      현금 및 현금성자산(요약)  ... EV/EBITDA 년_x 년+1         key                시간  \
27357             임시  ...        임시  임시  임시   318002000  2000-12-20 16:17   
27358             임시  ...        임시  임시  임시   318002000  2000-11-23 10:19   
27359             임시  ...        임시  임시  임시   318002000  2000-03-28 00:00   
27360             임시  ...        임시  임시  임시   318002000  2000-03-28 00:00   
27361             임시  ...        임시  임시  임시   338502000  2000-08-07 15:44   
27362             임시  ...        임시  임시  임시   333102000  2000-06-29 10:33   
27363             임시  ...        임시  임시  임시   333102000  2000-01-31 00:00   
27364             임시  ...        임시  임시  임시   133102000  2000-03-31 00:00   
27365             임시  ...        임시  임시  임시   283002000  2000-03-31 00:00   
27366             임시  ...        임시  임시  임시   283002000  2000-02-09 00:00   
27367             임시  ...        임시  임시  임시   283002000  2000-02-09 00:00   
27368             임시  ...        임시  임시  임시   192602000  2000-03-23 00:00   
27369             임시  ...        임시  임시  임시   540202010  2010-03-23 14:29   
27370             임시  ...        임시  임시  임시   801402010  2010-01-26 14:34   
27371             임시  ...        임시  임시  임시   372402012  2012-03-15 19:32   
27372             임시  ...        임시  임시  임시   454702012  2012-03-15 18:24   
27373             임시  ...        임시  임시  임시  1019702015  2015-03-04 16:49   
27374             임시  ...        임시  임시  임시  1019702015  2015-03-02 18:15   
27375             임시  ...        임시  임시  임시   336002020  2020-11-17 16:01   
27376             임시  ...        임시  임시  임시   336002020  2020-09-02 15:40   
27377             임시  ...        임시  임시  임시   862502020  2020-07-28 14:54   
27378             임시  ...        임시  임시  임시   862502020  2020-05-08 15:03   

           회사명_y      종목코드                          공시제목        제출인   년_y  
27357       ST&I   31800.0                    회사정리절차종결결정     에스티앤아이  2000  
27358       ST&I   31800.0                    회사정리절차종결신청     에스티앤아이  2000  
27359       ST&I   31800.0    회사정리절차개시결정(씨티아이반도체(주) (1))         임시  2000  
27360       ST&I   31800.0    회사정리절차개시결정(씨티아이반도체(주) (2))         임시  2000  
27361      지노시스템   33850.0                 화의채무변제완료보고서제출      지노시스템  2000  
27362        엠투엔   33310.0                 화의채무변제완료보고서제출        엠투엔  2000  
27363        엠투엔   33310.0               은행거래재개((주)우진산전)         임시 

In [228]:
merged.head()

회사명_x    거래소코드     회계년도 소속코드 상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약) 당좌자산(요약)  \
0  (주)CMG제약  58820.0  2000/12  5.0    임시     UQ  28990.0  21169.0  10541.0   
1  (주)CMG제약  58820.0  2001/12  5.0    임시     UQ  20908.0  16359.0   2307.0   
2  (주)CMG제약  58820.0  2002/12  5.0    임시     UQ  15401.0   9880.0   1436.0   
3  (주)CMG제약  58820.0  2003/12  5.0    임시     UQ  11063.0   8534.0   1083.0   
4  (주)CMG제약  58820.0  2004/12  5.0    임시     UQ   5179.0   3893.0    445.0   

  현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  시간 회사명_y 종목코드 공시제목  \
0         4330.0  ...        임시  2000  2001.0  588202001  임시    임시   임시   임시   
1         1829.0  ...        임시  2001  2002.0  588202002  임시    임시   임시   임시   
2          355.0  ...        임시  2002  2003.0  588202003  임시    임시   임시   임시   
3            2.0  ...        임시  2003  2004.0  588202004  임시    임시   임시   임시   
4           11.0  ...        임시  2004  2005.0  588202005  임시    임시   임시   임시   

  제출인 년_y  
0  임시  임시  
1  임시  임시  
2  임시  임시  
3  임시  임시  
4  임시  임시  

[5 rows x 276 columns]

In [43]:
print('train에 반영되지않은 부도회사 명 : ','\n', merged[merged['회사명_x']=='임시']['회사명_y'].unique())
print('-------------------------------------------------------------------')
print('train에 반영되지않은 부도회사 코드 : ', '\n', merged[merged['소속코드']=='임시']['종목코드'].unique())
print('-------------------------------------------------------------------')
print('train에 반영되지않은 부도회사 계 : ', merged[merged['회사명_x']=='임시']['회사명_y'].nunique())

train에 반영되지않은 부도회사 명 :  
 ['ST&I' '지노시스템' '엠투엔' '아진산업' '에이치엘비' '엔케이바이오' 'GK파워' '디보스' '평안물산'
 '에이프로테크놀로지' '우양에이치씨' '럭슬' '이노와이즈']
-------------------------------------------------------------------
train에 반영되지않은 부도회사 코드 :  
 [31800.0 33850.0 33310.0 13310.0 28300.0 19260.0 54020.0 80140.0 37240.0
 45470.0 101970.0 33600.0 86250.0]
-------------------------------------------------------------------
train에 반영되지않은 부도회사 계 :  13


## train에 반영되지않은 부도기업 13개 공시제목 채워넣기<br>
<span style="color:yellow">처리한 내역</span><br>
-31800.0 	(주)에스티앤아이<br>
-33850.0    (주)지노시스템<br>
-54020.0    (주)지케이파워<br>
-37240.0    평안물산(주)<br>
-45470.0    (주)에이프로테크놀로지<br>
-101970.0   우양에이치씨(주)<br>
-33600.0    럭슬(주)<br>
-86250.0    (주)화신테크<br>
<br>
-28300.0    에이치엘비(주)	<br>
-19260.0    (주)엔케이바이오<br>
-80140.0    (주)디보스<br>

<span style="color:red">**특이사항**</span><br>
-33310.0    (주)엠투엔 00년에 채무변제완료 후 은행거래 재개 -> 부도기업 아님으로 판단<br>
-13310.0    아진산업(주) -> 회사정리절차개시결정 후 20년간 영업중. 부도기업인지 아닌지 고려해봐야함

### st&i 31800.0

In [48]:
merged.loc[merged['거래소코드']==31800.0]

회사명_x    거래소코드     회계년도 소속코드       상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약)  \
9016  (주)에스티앤아이  31800.0  2000/12  4.0  2009/07/01     UQ  39665.0   3256.0   
9017  (주)에스티앤아이  31800.0  2001/12  4.0  2009/07/01     UQ  34205.0   2258.0   
9018  (주)에스티앤아이  31800.0  2002/12  4.0  2009/07/01     UQ  67242.0  37320.0   
9019  (주)에스티앤아이  31800.0  2003/12  4.0  2009/07/01     UQ  51446.0  17927.0   
9020  (주)에스티앤아이  31800.0  2004/12  4.0  2009/07/01     UQ  42000.0  11661.0   
9021  (주)에스티앤아이  31800.0  2005/12  4.0  2009/07/01     UQ  34047.0   6314.0   
9022  (주)에스티앤아이  31800.0  2006/12  4.0  2009/07/01     UQ  57281.0  16155.0   
9023  (주)에스티앤아이  31800.0  2007/12  4.0  2009/07/01     UQ  65077.0  26264.0   
9024  (주)에스티앤아이  31800.0  2008/12  4.0  2009/07/01     UQ   8326.0   1243.0   

     당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  시간  \
9016   2928.0          511.0  ...        임시  2000  2001.0  318002001  임시   
9017   1407.0           61.0  ...        임시  2001  2002.0  318002002  임시   
9018  12111.0         1054.0  ...        임시  2002  2003.0  318002003  임시   
9019  10882.0         2569.0  ...        임시  2003  2004.0  318002004  임시   
9020  10886.0         9555.0  ...        임시  2004  2005.0  318002005  임시   
9021   4646.0          150.0  ...        임시  2005  2006.0  318002006  임시   
9022  13271.0         1507.0  ...        임시  2006  2007.0  318002007  임시   
9023  24626.0          204.0  ...       0.0  2007  2008.0  318002008  임시   
9024   1243.0           36.0  ...        임시  2008  2009.0  318002009  임시   

     회사명_y 종목코드 공시제목 제출인 년_y  
9016    임시   임시   임시  임시  임시  
9017    임시   임시   임시  임시  임시  
9018    임시   임시   임시  임시  임시  
9019    임시   임시   임시  임시  임시  
9020    임시   임시   임시  임시  임시  
9021    임시   임시   임시  임시  임시  
9022    임시   임시   임시  임시  임시  
9023    임시   임시   임시  임시  임시  
9024    임시   임시   임시  임시  임시  

[9 rows x 276 columns]

In [49]:
merged.loc[merged['종목코드']==31800.0]

회사명_x 거래소코드 회계년도 소속코드 상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약) 당좌자산(요약)  \
27357    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27358    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27359    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27360    임시    임시   임시   임시    임시     임시       임시       임시       임시   

      현금 및 현금성자산(요약)  ... EV/EBITDA 년_x 년+1        key                시간  \
27357             임시  ...        임시  임시  임시  318002000  2000-12-20 16:17   
27358             임시  ...        임시  임시  임시  318002000  2000-11-23 10:19   
27359             임시  ...        임시  임시  임시  318002000  2000-03-28 00:00   
27360             임시  ...        임시  임시  임시  318002000  2000-03-28 00:00   

      회사명_y     종목코드                        공시제목     제출인   년_y  
27357  ST&I  31800.0                  회사정리절차종결결정  에스티앤아이  2000  
27358  ST&I  31800.0                  회사정리절차종결신청  에스티앤아이  2000  
27359  ST&I  31800.0  회사정리절차개시결정(씨티아이반도체(주) (1))      임시  2000  
27360  ST&I  31800.0  회사정리절차개시결정(씨티아이반도체(주) (2))      임시  2000  

[4 rows x 276 columns]

In [50]:
merged.loc[merged['key']=='318002000', '공시제목'] = '회사정리절차종결결정'

### **엠투엔** 33310.0 -> 부도기업 아닌걸로 판단 

In [51]:
merged.loc[merged['거래소코드']==33310.0]

회사명_x    거래소코드     회계년도 소속코드 상장폐지일 감사의견코드  자산총계(요약) 유동자산(요약) 당좌자산(요약)  \
10414  (주)엠투엔  33310.0  2000/12  5.0    임시     QG   21993.0   9456.0   5107.0   
10415  (주)엠투엔  33310.0  2001/12  5.0    임시     UQ   23635.0   9988.0   5819.0   
10416  (주)엠투엔  33310.0  2002/12  5.0    임시     UQ   29815.0  15254.0   8024.0   
10417  (주)엠투엔  33310.0  2003/12  5.0    임시     UQ   23895.0  14267.0   6723.0   
10418  (주)엠투엔  33310.0  2004/12  5.0    임시     UQ   24814.0  14154.0   6537.0   
10419  (주)엠투엔  33310.0  2005/12  5.0    임시     UQ   25800.0  14601.0   7325.0   
10420  (주)엠투엔  33310.0  2006/12  5.0    임시     UQ   28862.0  17819.0   9946.0   
10421  (주)엠투엔  33310.0  2007/12  5.0    임시     UQ   61285.0  18852.0  13862.0   
10422  (주)엠투엔  33310.0  2008/12  5.0    임시     UQ   73832.0  24728.0  10373.0   
10423  (주)엠투엔  33310.0  2009/12  5.0    임시     UQ   67139.0  21664.0  12380.0   
10424  (주)엠투엔  33310.0  2010/12  5.0    임시     UQ   69463.0  21189.0  13430.0   
10425  (주)엠투엔  33310.0  2011/12  5.0    임시     UQ   73308.0  21803.0  12206.0   
10426  (주)엠투엔  33310.0  2012/12  5.0    임시     UQ   55697.0  12941.0  11161.0   
10427  (주)엠투엔  33310.0  2013/12  5.0    임시     UQ   55332.0  10015.0   7458.0   
10428  (주)엠투엔  33310.0  2014/12  5.0    임시     UQ   64814.0   9783.0   7341.0   
10429  (주)엠투엔  33310.0  2015/12  5.0    임시     UQ   68935.0   7511.0   4855.0   
10430  (주)엠투엔  33310.0  2016/12  5.0    임시     UQ   74834.0   8390.0   6276.0   
10431  (주)엠투엔  33310.0  2017/12  5.0    임시     UQ   78823.0   8081.0   6148.0   
10432  (주)엠투엔  33310.0  2018/12  5.0    임시     UQ   87009.0  13515.0   9845.0   
10433  (주)엠투엔  33310.0  2019/12  5.0    임시     UQ   90578.0  10104.0   8118.0   
10434  (주)엠투엔  33310.0  2020/12  5.0    임시     UQ  112327.0  13261.0  11612.0   

      현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  시간 회사명_y 종목코드  \
10414            4.0  ...        임시  2000  2001.0  333102001  임시    임시   임시   
10415          681.0  ...        임시  2001  2002.0  333102002  임시    임시   임시   
10416          383.0  ...        임시  2002  2003.0  333102003  임시    임시   임시   
10417          378.0  ...        임시  2003  2004.0  333102004  임시    임시   임시   
10418         1071.0  ...        임시  2004  2005.0  333102005  임시    임시   임시   
10419          997.0  ...        임시  2005  2006.0  333102006  임시    임시   임시   
10420         1343.0  ...        임시  2006  2007.0  333102007  임시    임시   임시   
10421         3770.0  ...     86.41  2007  2008.0  333102008  임시    임시   임시   
10422           91.0  ...      9.46  2008  2009.0  333102009  임시    임시   임시   
10423         2726.0  ...     41.78  2009  2010.0  333102010  임시    임시   임시   
10424          427.0  ...     18.85  2010  2011.0  333102011  임시    임시   임시   
10425          399.0  ...     28.78  2011  2012.0  333102012  임시    임시   임시   
10426           48.0  ...     11.56  2012  2013.0  333102013  임시    임시   임시   
10427            3.0  ...      8.87  2013  2014.0  333102014  임시    임시   임시   
10428           11.0  ...     11.11  2014  2015.0  333102015  임시    임시   임시   
10429            0.0  ...      27.7  2015  2016.0  333102016  임시    임시   임시   
10430          752.0  ...     33.22  2016  2017.0  333102017  임시    임시   임시   
10431          633.0  ...     41.58  2017  2018.0  333102018  임시    임시   임시   
10432          618.0  ...     48.75  2018  2019.0  333102019  임시    임시   임시   
10433         1733.0  ...     88.02  2019  2020.0  333102020  임시    임시   임시   
10434         4825.0  ...       0.0  2020  2021.0  333102021  임시    임시   임시   

      공시제목 제출인 년_y  
10414   임시  임시  임시  
10415   임시  임시  임시  
10416   임시  임시  임시  
10417   임시  임시  임시  
10418   임시  임시  임시  
10419   임시  임시  임시  
10420   임시  임시  임시  
10421   임시  임시  임시  
10422   임시  임시  임시  
10423   임시  임시  임시  
10424   임시  임시  임시  
10425   임시  임시  임시  
10426   임시  임시  임시  
10427   임시  임시  임시  
10428   임시  임시  임시  
10429   임시  임시  임시  
10430   임시  임시  임시  
10431   임시  임시  임시  
10432   임시  임시  임시  
10433   임시  임시  임시  
10434   임시  임시  임시  

[21 rows x 276 columns]

In [52]:
merged[merged['종목코드']==33310.0]

회사명_x 거래소코드 회계년도 소속코드 상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약) 당좌자산(요약)  \
27362    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27363    임시    임시   임시   임시    임시     임시       임시       임시       임시   

      현금 및 현금성자산(요약)  ... EV/EBITDA 년_x 년+1        key                시간  \
27362             임시  ...        임시  임시  임시  333102000  2000-06-29 10:33   
27363             임시  ...        임시  임시  임시  333102000  2000-01-31 00:00   

      회사명_y     종목코드             공시제목  제출인   년_y  
27362   엠투엔  33310.0    화의채무변제완료보고서제출  엠투엔  2000  
27363   엠투엔  33310.0  은행거래재개((주)우진산전)   임시  2000  

[2 rows x 276 columns]

In [53]:
merged.loc[merged['key'] == '333102021', '공시제목'] = '화의채무변제완료보고서제출'

### 지노 33850.0 화의채무변제완료보고서제출

In [57]:
merged.loc[merged['거래소코드'] == 33850.0]

회사명_x    거래소코드     회계년도 소속코드       상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약)  \
14214  (주)지노시스템  33850.0  2000/12  4.0  2011/05/07     QG  13655.0   8846.0   
14215  (주)지노시스템  33850.0  2001/12  4.0  2011/05/07     UQ  22179.0  15593.0   
14216  (주)지노시스템  33850.0  2002/12  4.0  2011/05/07     UQ  25466.0  17229.0   
14217  (주)지노시스템  33850.0  2003/12  4.0  2011/05/07     UQ  26862.0  17129.0   
14218  (주)지노시스템  33850.0  2004/12  4.0  2011/05/07     UQ  16319.0   8982.0   
14219  (주)지노시스템  33850.0  2005/12  4.0  2011/05/07     UQ  19363.0   7509.0   
14220  (주)지노시스템  33850.0  2006/12  4.0  2011/05/07     UQ  22226.0  13669.0   
14221  (주)지노시스템  33850.0  2007/12  4.0  2011/05/07     UQ  30430.0  17580.0   
14222  (주)지노시스템  33850.0  2008/12  4.0  2011/05/07     UQ  26845.0  12301.0   
14223  (주)지노시스템  33850.0  2009/12  4.0  2011/05/07     UQ  20577.0   7062.0   
14224  (주)지노시스템  33850.0  2010/12  4.0  2011/05/07     DS  34650.0  23288.0   

      당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  시간  \
14214   7485.0         1919.0  ...        임시  2000  2001.0  338502001  임시   
14215  14762.0         2219.0  ...        임시  2001  2002.0  338502002  임시   
14216  15134.0         2891.0  ...        임시  2002  2003.0  338502003  임시   
14217  16437.0         1644.0  ...        임시  2003  2004.0  338502004  임시   
14218   8494.0           41.0  ...        임시  2004  2005.0  338502005  임시   
14219   7218.0          174.0  ...        임시  2005  2006.0  338502006  임시   
14220  13502.0         5023.0  ...        임시  2006  2007.0  338502007  임시   
14221  17538.0         4681.0  ...       0.0  2007  2008.0  338502008  임시   
14222  10110.0         2261.0  ...        임시  2008  2009.0  338502009  임시   
14223   6347.0         3359.0  ...        임시  2009  2010.0  338502010  임시   
14224  18166.0          365.0  ...        임시  2010  2011.0  338502011  임시   

      회사명_y 종목코드           공시제목 제출인 년_y  
14214    임시   임시             임시  임시  임시  
14215    임시   임시             임시  임시  임시  
14216    임시   임시             임시  임시  임시  
14217    임시   임시             임시  임시  임시  
14218    임시   임시             임시  임시  임시  
14219    임시   임시             임시  임시  임시  
14220    임시   임시             임시  임시  임시  
14221    임시   임시             임시  임시  임시  
14222    임시   임시             임시  임시  임시  
14223    임시   임시             임시  임시  임시  
14224    임시   임시  화의채무변제완료보고서제출  임시  임시  

[11 rows x 276 columns]

In [55]:
merged.loc[merged['종목코드'] == 33850.0]

회사명_x 거래소코드 회계년도 소속코드 상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약) 당좌자산(요약)  \
27361    임시    임시   임시   임시    임시     임시       임시       임시       임시   

      현금 및 현금성자산(요약)  ... EV/EBITDA 년_x 년+1        key                시간  \
27361             임시  ...        임시  임시  임시  338502000  2000-08-07 15:44   

       회사명_y     종목코드           공시제목    제출인   년_y  
27361  지노시스템  33850.0  화의채무변제완료보고서제출  지노시스템  2000  

[1 rows x 276 columns]

In [56]:
merged.loc[merged['key'] == '338502011', '공시제목'] = '화의채무변제완료보고서제출'

### **아진산업** 13310.0 -다시 보기 임시친구 -> 회사정리절차개시결정 후 20년간 영업중 고려해봐야함

In [63]:
merged.loc[merged['거래소코드'] == 13310.0]

회사명_x    거래소코드     회계년도 소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
22951  아진산업(주)  13310.0  2002/12  5.0    임시     UQ   22950.0    8013.0   
22952  아진산업(주)  13310.0  2003/12  5.0    임시     UQ   21161.0    7393.0   
22953  아진산업(주)  13310.0  2004/12  5.0    임시     UQ   20043.0    4902.0   
22954  아진산업(주)  13310.0  2005/12  5.0    임시     UQ   34809.0   11729.0   
22955  아진산업(주)  13310.0  2006/12  5.0    임시     UQ   37867.0    6117.0   
22956  아진산업(주)  13310.0  2007/12  5.0    임시     UQ   45183.0    8901.0   
22957  아진산업(주)  13310.0  2008/12  5.0    임시     UQ   91325.0   17752.0   
22958  아진산업(주)  13310.0  2009/12  5.0    임시     UQ  110853.0   32332.0   
22959  아진산업(주)  13310.0  2010/12  5.0    임시     UQ  150757.0   54306.0   
22960  아진산업(주)  13310.0  2011/12  5.0    임시     UQ  187676.0   66664.0   
22961  아진산업(주)  13310.0  2012/12  5.0    임시     UQ  196791.0   71939.0   
22962  아진산업(주)  13310.0  2013/12  5.0    임시     UQ  219825.0   78530.0   
22963  아진산업(주)  13310.0  2014/12  5.0    임시     UQ  231295.0   75232.0   
22964  아진산업(주)  13310.0  2015/12  5.0    임시     UQ  272481.0   77752.0   
22965  아진산업(주)  13310.0  2016/12  5.0    임시     UQ  306968.0   84434.0   
22966  아진산업(주)  13310.0  2017/12  5.0    임시     UQ  346149.0   89888.0   
22967  아진산업(주)  13310.0  2018/12  5.0    임시     UQ  386491.0   86217.0   
22968  아진산업(주)  13310.0  2019/12  5.0    임시     UQ  447355.0  148487.0   
22969  아진산업(주)  13310.0  2020/12  5.0    임시     UQ  432699.0  155888.0   

       당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  시간  \
22951    7325.0          656.0  ...        임시  2002  2003.0  133102003  임시   
22952    6661.0            9.0  ...        임시  2003  2004.0  133102004  임시   
22953    4035.0         1665.0  ...        임시  2004  2005.0  133102005  임시   
22954   10733.0         6520.0  ...        임시  2005  2006.0  133102006  임시   
22955    4882.0            1.0  ...        임시  2006  2007.0  133102007  임시   
22956    7359.0          466.0  ...      1.45  2007  2008.0  133102008  임시   
22957   15222.0          272.0  ...      3.74  2008  2009.0  133102009  임시   
22958   29509.0          246.0  ...      3.48  2009  2010.0  133102010  임시   
22959   46940.0         5377.0  ...      2.74  2010  2011.0  133102011  임시   
22960   64329.0          434.0  ...       2.2  2011  2012.0  133102012  임시   
22961   68804.0          267.0  ...      1.72  2012  2013.0  133102013  임시   
22962   73115.0          219.0  ...       5.3  2013  2014.0  133102014  임시   
22963   71651.0          186.0  ...      2.28  2014  2015.0  133102015  임시   
22964   74647.0          296.0  ...       3.8  2015  2016.0  133102016  임시   
22965   80739.0          559.0  ...      7.31  2016  2017.0  133102017  임시   
22966   81712.0          284.0  ...      8.84  2017  2018.0  133102018  임시   
22967   78107.0          953.0  ...     25.84  2018  2019.0  133102019  임시   
22968  137282.0        13361.0  ...       5.1  2019  2020.0  133102020  임시   
22969  142965.0        22910.0  ...      5.59  2020  2021.0  133102021  임시   

      회사명_y 종목코드 공시제목 제출인 년_y  
22951    임시   임시   임시  임시  임시  
22952    임시   임시   임시  임시  임시  
22953    임시   임시   임시  임시  임시  
22954    임시   임시   임시  임시  임시  
22955    임시   임시   임시  임시  임시  
22956    임시   임시   임시  임시  임시  
22957    임시   임시   임시  임시  임시  
22958    임시   임시   임시  임시  임시  
22959    임시   임시   임시  임시  임시  
22960    임시   임시   임시  임시  임시  
22961    임시   임시   임시  임시  임시  
22962    임시   임시   임시  임시  임시  
22963    임시   임시   임시  임시  임시  
22964    임시   임시   임시  임시  임시  
22965    임시   임시   임시  임시  임시  
22966    임시   임시   임시  임시  임시  
22967    임시   임시   임시  임시  임시  
22968    임시   임시   임시  임시  임시  
22969    임시   임시   임시  임시  임시  

[19 rows x 276 columns]

In [59]:
merged.loc[merged['종목코드'] == 13310.0]

회사명_x 거래소코드 회계년도 소속코드 상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약) 당좌자산(요약)  \
27364    임시    임시   임시   임시    임시     임시       임시       임시       임시   

      현금 및 현금성자산(요약)  ... EV/EBITDA 년_x 년+1        key                시간  \
27364             임시  ...        임시  임시  임시  133102000  2000-03-31 00:00   

      회사명_y     종목코드                 공시제목 제출인   년_y  
27364  아진산업  13310.0  회사정리절차개시결정(아진산업(주))  임시  2000  

[1 rows x 276 columns]

In [65]:
merged.loc[merged['key'] == '133102021', '공시제목'] = '회사정리절차개시결정(아진산업(주))'

### **에이치엘비** 28300.0 2002 회사정리절차종결 BUT 2020까지 회사운영중

In [67]:
merged.loc[merged['거래소코드'] == 28300.0]

회사명_x    거래소코드     회계년도 소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
23576  에이치엘비(주)  28300.0  2000/12  5.0    임시     UQ   22460.0    3362.0   
23577  에이치엘비(주)  28300.0  2001/12  5.0    임시     UQ   17974.0    2380.0   
23578  에이치엘비(주)  28300.0  2001/12  5.0    임시     UQ   17974.0    2380.0   
23579  에이치엘비(주)  28300.0  2002/12  5.0    임시     UQ   16407.0    2497.0   
23580  에이치엘비(주)  28300.0  2003/12  5.0    임시     QG   11762.0     726.0   
23581  에이치엘비(주)  28300.0  2004/12  5.0    임시     UQ    2347.0    1768.0   
23582  에이치엘비(주)  28300.0  2005/12  5.0    임시     UQ   19044.0    7618.0   
23583  에이치엘비(주)  28300.0  2006/12  5.0    임시     UQ   27051.0   15420.0   
23584  에이치엘비(주)  28300.0  2007/12  5.0    임시     UQ   43462.0   27231.0   
23585  에이치엘비(주)  28300.0  2008/12  5.0    임시     UQ   50147.0   10165.0   
23586  에이치엘비(주)  28300.0  2009/12  5.0    임시     UQ   53819.0   18614.0   
23587  에이치엘비(주)  28300.0  2010/12  5.0    임시     UQ   35552.0   13134.0   
23588  에이치엘비(주)  28300.0  2011/12  5.0    임시     UQ   34276.0    9327.0   
23589  에이치엘비(주)  28300.0  2012/12  5.0    임시     UQ   31684.0    7171.0   
23590  에이치엘비(주)  28300.0  2013/12  5.0    임시     UQ   33835.0   16999.0   
23591  에이치엘비(주)  28300.0  2014/12  5.0    임시     UQ   51958.0   32847.0   
23592  에이치엘비(주)  28300.0  2015/12  5.0    임시     UQ   91734.0   20424.0   
23593  에이치엘비(주)  28300.0  2016/12  5.0    임시     UQ   87304.0   15912.0   
23594  에이치엘비(주)  28300.0  2017/12  5.0    임시     UQ  108127.0   16558.0   
23595  에이치엘비(주)  28300.0  2018/12  5.0    임시     UQ  238044.0   99004.0   
23596  에이치엘비(주)  28300.0  2019/12  5.0    임시     UQ  494081.0   40641.0   
23597  에이치엘비(주)  28300.0  2020/12  5.0    임시     UQ  791486.0  173521.0   

       당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  \
23576    1775.0          216.0  ...        임시  2000  2001.0  283002001   
23577    1243.0            3.0  ...        임시  2001  2002.0  283002002   
23578    1243.0            3.0  ...        임시  2001  2002.0  283002002   
23579    1990.0           30.0  ...        임시  2002  2003.0  283002003   
23580     645.0          303.0  ...        임시  2003  2004.0  283002004   
23581    1768.0           15.0  ...        임시  2004  2005.0  283002005   
23582    7318.0         3858.0  ...        임시  2005  2006.0  283002006   
23583   15063.0         7998.0  ...        임시  2006  2007.0  283002007   
23584   27209.0        13265.0  ...       0.0  2007  2008.0  283002008   
23585    9613.0          169.0  ...        임시  2008  2009.0  283002009   
23586   18039.0         1445.0  ...        임시  2009  2010.0  283002010   
23587   13042.0         1223.0  ...        임시  2010  2011.0  283002011   
23588    9291.0         2028.0  ...     60.61  2011  2012.0  283002012   
23589    7088.0          903.0  ...       0.0  2012  2013.0  283002013   
23590   12459.0         1049.0  ...       0.0  2013  2014.0  283002014   
23591   25174.0        10044.0  ...      88.3  2014  2015.0  283002015   
23592   15118.0         3492.0  ...       0.0  2015  2016.0  283002016   
23593   12058.0         8018.0  ...       0.0  2016  2017.0  283002017   
23594   12415.0         6970.0  ...       0.0  2017  2018.0  283002018   
23595   95948.0        13746.0  ...   1270.27  2018  2019.0  283002019   
23596   36613.0        13329.0  ...       0.0  2019  2020.0  283002020   
23597  169435.0       154000.0  ...       0.0  2020  2021.0  283002021   

                     시간  회사명_y     종목코드        공시제목    제출인   년_y  
23576                임시     임시       임시          임시     임시    임시  
23577  2002-05-21 18:16  에이치엘비  28300.0  회사정리절차종결결정  에이치엘비  2002  
23578  2002-04-17 17:42  에이치엘비  28300.0  회사정리절차종결신청  에이치엘비  2002  
23579                임시     임시       임시          임시     임시    임시  
23580                임시     임시       임시          임시     임시    임시  
23581                임시     임시       임시          임시     임시    임시  
23582                임시     임시       임시          임시     임시    임시  
23583                임시     임시       임시      

In [68]:
merged.loc[merged['종목코드'] == 28300.0]

회사명_x    거래소코드     회계년도 소속코드 상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약)  \
23577  에이치엘비(주)  28300.0  2001/12  5.0    임시     UQ  17974.0   2380.0   
23578  에이치엘비(주)  28300.0  2001/12  5.0    임시     UQ  17974.0   2380.0   
27365        임시       임시       임시   임시    임시     임시       임시       임시   
27366        임시       임시       임시   임시    임시     임시       임시       임시   
27367        임시       임시       임시   임시    임시     임시       임시       임시   

      당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  \
23577   1243.0            3.0  ...        임시  2001  2002.0  283002002   
23578   1243.0            3.0  ...        임시  2001  2002.0  283002002   
27365       임시             임시  ...        임시    임시      임시  283002000   
27366       임시             임시  ...        임시    임시      임시  283002000   
27367       임시             임시  ...        임시    임시      임시  283002000   

                     시간  회사명_y     종목코드                     공시제목    제출인   년_y  
23577  2002-05-21 18:16  에이치엘비  28300.0               회사정리절차종결결정  에이치엘비  2002  
23578  2002-04-17 17:42  에이치엘비  28300.0               회사정리절차종결신청  에이치엘비  2002  
27365  2000-03-31 00:00  에이치엘비  28300.0          은행거래재개(국제정공(주))     임시  2000  
27366  2000-02-09 00:00  에이치엘비  28300.0  회사정리절차개시결정(국제정공(주) (1))     임시  2000  
27367  2000-02-09 00:00  에이치엘비  28300.0  회사정리절차개시결정(국제정공(주) (2))     임시  2000  

[5 rows x 276 columns]

In [45]:
merged[merged['종목코드']==28300.0]

회사명_x    거래소코드     회계년도 소속코드 상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약)  \
23577  에이치엘비(주)  28300.0  2001/12  5.0    임시     UQ  17974.0   2380.0   
23578  에이치엘비(주)  28300.0  2001/12  5.0    임시     UQ  17974.0   2380.0   
27365        임시       임시       임시   임시    임시     임시       임시       임시   
27366        임시       임시       임시   임시    임시     임시       임시       임시   
27367        임시       임시       임시   임시    임시     임시       임시       임시   

      당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  \
23577   1243.0            3.0  ...        임시  2001  2002.0  283002002   
23578   1243.0            3.0  ...        임시  2001  2002.0  283002002   
27365       임시             임시  ...        임시    임시      임시  283002000   
27366       임시             임시  ...        임시    임시      임시  283002000   
27367       임시             임시  ...        임시    임시      임시  283002000   

                     시간  회사명_y     종목코드                     공시제목    제출인   년_y  
23577  2002-05-21 18:16  에이치엘비  28300.0               회사정리절차종결결정  에이치엘비  2002  
23578  2002-04-17 17:42  에이치엘비  28300.0               회사정리절차종결신청  에이치엘비  2002  
27365  2000-03-31 00:00  에이치엘비  28300.0          은행거래재개(국제정공(주))     임시  2000  
27366  2000-02-09 00:00  에이치엘비  28300.0  회사정리절차개시결정(국제정공(주) (1))     임시  2000  
27367  2000-02-09 00:00  에이치엘비  28300.0  회사정리절차개시결정(국제정공(주) (2))     임시  2000  

[5 rows x 276 columns]

### **엔케이바이오** 19260.0 ->채무변제완료 및 은행거래 재개

In [69]:
merged.loc[merged['거래소코드'] == 19260.0]

회사명_x    거래소코드     회계년도 소속코드       상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약)  \
10017  (주)엔케이바이오  19260.0  2000/12  4.0  2012/09/05     UQ  31785.0   7360.0   
10018  (주)엔케이바이오  19260.0  2001/12  4.0  2012/09/05     UQ  26915.0   5537.0   
10019  (주)엔케이바이오  19260.0  2002/12  4.0  2012/09/05     UQ  24184.0   4948.0   
10020  (주)엔케이바이오  19260.0  2003/12  4.0  2012/09/05     UQ  23685.0   7548.0   
10021  (주)엔케이바이오  19260.0  2004/12  4.0  2012/09/05     UQ  37651.0  10036.0   
10022  (주)엔케이바이오  19260.0  2005/12  4.0  2012/09/05     UQ  43491.0  12572.0   
10023  (주)엔케이바이오  19260.0  2006/12  4.0  2012/09/05     UQ  54911.0  20037.0   
10024  (주)엔케이바이오  19260.0  2007/12  4.0  2012/09/05     UQ  40157.0  10451.0   
10025  (주)엔케이바이오  19260.0  2008/12  4.0  2012/09/05     UQ  48850.0   6408.0   
10026  (주)엔케이바이오  19260.0  2009/12  4.0  2012/09/05     UQ  46809.0   6424.0   
10027  (주)엔케이바이오  19260.0  2010/12  4.0  2012/09/05     UQ  48744.0  15419.0   
10028  (주)엔케이바이오  19260.0  2011/12  4.0  2012/09/05     QU  53101.0  16161.0   

      당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  \
10017   5442.0          540.0  ...        임시  2000  2001.0  192602001   
10018   4495.0          719.0  ...        임시  2001  2002.0  192602002   
10019   3687.0          464.0  ...        임시  2002  2003.0  192602003   
10020   6099.0         1321.0  ...        임시  2003  2004.0  192602004   
10021   8051.0         1704.0  ...        임시  2004  2005.0  192602005   
10022  10307.0         3095.0  ...        임시  2005  2006.0  192602006   
10023  18054.0         7822.0  ...        임시  2006  2007.0  192602007   
10024   8221.0         1348.0  ...       0.0  2007  2008.0  192602008   
10025   6017.0         1430.0  ...       0.0  2008  2009.0  192602009   
10026   5890.0          892.0  ...       0.0  2009  2010.0  192602010   
10027  14573.0         1878.0  ...        임시  2010  2011.0  192602011   
10028  15557.0         2892.0  ...     27.55  2011  2012.0  192602012   

                     시간   회사명_y     종목코드           공시제목 제출인   년_y  
10017  2001-02-22 18:34  엔케이바이오  19260.0  화의채무변제완료보고서제출  셀텍  2001  
10018                임시      임시       임시             임시  임시    임시  
10019                임시      임시       임시             임시  임시    임시  
10020                임시      임시       임시             임시  임시    임시  
10021                임시      임시       임시             임시  임시    임시  
10022                임시      임시       임시             임시  임시    임시  
10023                임시      임시       임시             임시  임시    임시  
10024                임시      임시       임시             임시  임시    임시  
10025                임시      임시       임시             임시  임시    임시  
10026                임시      임시       임시             임시  임시    임시  
10027                임시      임시       임시             임시  임시    임시  
10028                임시      임시       임시             임시  임시    임시  

[12 rows x 276 columns]

In [46]:
merged.loc[merged['종목코드'] == 19260.0]

회사명_x    거래소코드     회계년도 소속코드       상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약)  \
10017  (주)엔케이바이오  19260.0  2000/12  4.0  2012/09/05     UQ  31785.0   7360.0   
27368         임시       임시       임시   임시          임시     임시       임시       임시   

      당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  \
10017   5442.0          540.0  ...        임시  2000  2001.0  192602001   
27368       임시             임시  ...        임시    임시      임시  192602000   

                     시간   회사명_y     종목코드           공시제목 제출인   년_y  
10017  2001-02-22 18:34  엔케이바이오  19260.0  화의채무변제완료보고서제출  셀텍  2001  
27368  2000-03-23 00:00  엔케이바이오  19260.0  은행거래재개((주)한올)  임시  2000  

[2 rows x 276 columns]

### GK파워 54020.0

In [73]:
merged.loc[merged['거래소코드'] == 54020.0]

회사명_x    거래소코드     회계년도 소속코드       상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약)  \
14469  (주)지케이파워  54020.0  2001/12  4.0  2010/04/03     UQ  23774.0  15963.0   
14470  (주)지케이파워  54020.0  2002/12  4.0  2010/04/03     UQ  32779.0  14046.0   
14471  (주)지케이파워  54020.0  2003/12  4.0  2010/04/03     UQ  21193.0   8242.0   
14472  (주)지케이파워  54020.0  2004/12  4.0  2010/04/03     UQ  12669.0   4478.0   
14473  (주)지케이파워  54020.0  2005/12  4.0  2010/04/03     UQ  10098.0   4202.0   
14474  (주)지케이파워  54020.0  2006/12  4.0  2010/04/03     UQ   9923.0   3973.0   
14475  (주)지케이파워  54020.0  2007/12  4.0  2010/04/03     UQ   8611.0   3311.0   
14476  (주)지케이파워  54020.0  2008/12  4.0  2010/04/03     UQ  23590.0  19464.0   

      당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  시간  \
14469   9485.0         2031.0  ...        임시  2001  2002.0  540202002  임시   
14470   8254.0         3281.0  ...        임시  2002  2003.0  540202003  임시   
14471   5079.0         1966.0  ...        임시  2003  2004.0  540202004  임시   
14472   3210.0          177.0  ...        임시  2004  2005.0  540202005  임시   
14473   2169.0          758.0  ...        임시  2005  2006.0  540202006  임시   
14474   2704.0          507.0  ...        임시  2006  2007.0  540202007  임시   
14475   2994.0          127.0  ...       0.0  2007  2008.0  540202008  임시   
14476  19121.0           17.0  ...        임시  2008  2009.0  540202009  임시   

      회사명_y 종목코드  공시제목 제출인 년_y  
14469    임시   임시    임시  임시  임시  
14470    임시   임시    임시  임시  임시  
14471    임시   임시    임시  임시  임시  
14472    임시   임시    임시  임시  임시  
14473    임시   임시    임시  임시  임시  
14474    임시   임시    임시  임시  임시  
14475    임시   임시    임시  임시  임시  
14476    임시   임시  부도발생  임시  임시  

[8 rows x 276 columns]

In [71]:
merged.loc[merged['종목코드'] == 54020.0]

회사명_x 거래소코드 회계년도 소속코드 상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약) 당좌자산(요약)  \
27369    임시    임시   임시   임시    임시     임시       임시       임시       임시   

      현금 및 현금성자산(요약)  ... EV/EBITDA 년_x 년+1        key                시간  \
27369             임시  ...        임시  임시  임시  540202010  2010-03-23 14:29   

      회사명_y     종목코드  공시제목    제출인   년_y  
27369  GK파워  54020.0  부도발생  지케이파워  2010  

[1 rows x 276 columns]

In [72]:
merged.loc[merged['key'] == '540202009', '공시제목'] = '부도발생'

### 디보스 80140.0

In [74]:
merged.loc[merged['거래소코드'] == 80140.0]

회사명_x    거래소코드     회계년도 소속코드       상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약)  \
2242  (주)디보스  80140.0  2002/12  4.0  2010/02/02     UQ  12254.0   7505.0   
2243  (주)디보스  80140.0  2003/12  4.0  2010/02/02     UQ  22113.0  14942.0   
2244  (주)디보스  80140.0  2004/12  4.0  2010/02/02     UQ  39390.0  28852.0   
2245  (주)디보스  80140.0  2005/12  4.0  2010/02/02     UQ  61574.0  40417.0   
2246  (주)디보스  80140.0  2006/12  4.0  2010/02/02     UQ  74910.0  49939.0   
2247  (주)디보스  80140.0  2007/12  4.0  2010/02/02     UQ  85008.0  56026.0   
2248  (주)디보스  80140.0  2008/12  4.0  2010/02/02     UQ  41196.0  11050.0   
2249  (주)디보스  80140.0  2008/12  4.0  2010/02/02     UQ  41196.0  11050.0   
2250  (주)디보스  80140.0  2008/12  4.0  2010/02/02     UQ  41196.0  11050.0   
2251  (주)디보스  80140.0  2008/12  4.0  2010/02/02     UQ  41196.0  11050.0   
2252  (주)디보스  80140.0  2008/12  4.0  2010/02/02     UQ  41196.0  11050.0   

     당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  \
2242   3407.0         1699.0  ...        임시  2002  2003.0  801402003   
2243   8272.0          544.0  ...        임시  2003  2004.0  801402004   
2244  21590.0          277.0  ...        임시  2004  2005.0  801402005   
2245  20690.0           78.0  ...        임시  2005  2006.0  801402006   
2246  27833.0         3809.0  ...        임시  2006  2007.0  801402007   
2247  34775.0         7846.0  ...       0.0  2007  2008.0  801402008   
2248   4103.0           45.0  ...        임시  2008  2009.0  801402009   
2249   4103.0           45.0  ...        임시  2008  2009.0  801402009   
2250   4103.0           45.0  ...        임시  2008  2009.0  801402009   
2251   4103.0           45.0  ...        임시  2008  2009.0  801402009   
2252   4103.0           45.0  ...        임시  2008  2009.0  801402009   

                    시간 회사명_y     종목코드             공시제목  제출인   년_y  
2242                임시    임시       임시               임시   임시    임시  
2243                임시    임시       임시               임시   임시    임시  
2244                임시    임시       임시               임시   임시    임시  
2245                임시    임시       임시               임시   임시    임시  
2246                임시    임시       임시               임시   임시    임시  
2247                임시    임시       임시               임시   임시    임시  
2248  2009-08-11 17:24   디보스  80140.0     [정정]회생절차개시결정  디보스  2009  
2249  2009-07-21 16:44   디보스  80140.0  [정정]회생절차개시결정[정]  디보스  2009  
2250  2009-06-17 15:12   디보스  80140.0  [정정]회생절차개시결정[정]  디보스  2009  
2251  2009-04-21 15:07   디보스  80140.0      회생절차개시결정[정]  디보스  2009  
2252  2009-04-07 17:55   디보스  80140.0         회생절차개시신청  디보스  2009  

[11 rows x 276 columns]

In [75]:
merged.loc[merged['종목코드'] == 80140.0]

회사명_x    거래소코드     회계년도 소속코드       상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약)  \
2248   (주)디보스  80140.0  2008/12  4.0  2010/02/02     UQ  41196.0  11050.0   
2249   (주)디보스  80140.0  2008/12  4.0  2010/02/02     UQ  41196.0  11050.0   
2250   (주)디보스  80140.0  2008/12  4.0  2010/02/02     UQ  41196.0  11050.0   
2251   (주)디보스  80140.0  2008/12  4.0  2010/02/02     UQ  41196.0  11050.0   
2252   (주)디보스  80140.0  2008/12  4.0  2010/02/02     UQ  41196.0  11050.0   
27370      임시       임시       임시   임시          임시     임시       임시       임시   

      당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  \
2248    4103.0           45.0  ...        임시  2008  2009.0  801402009   
2249    4103.0           45.0  ...        임시  2008  2009.0  801402009   
2250    4103.0           45.0  ...        임시  2008  2009.0  801402009   
2251    4103.0           45.0  ...        임시  2008  2009.0  801402009   
2252    4103.0           45.0  ...        임시  2008  2009.0  801402009   
27370       임시             임시  ...        임시    임시      임시  801402010   

                     시간 회사명_y     종목코드             공시제목  제출인   년_y  
2248   2009-08-11 17:24   디보스  80140.0     [정정]회생절차개시결정  디보스  2009  
2249   2009-07-21 16:44   디보스  80140.0  [정정]회생절차개시결정[정]  디보스  2009  
2250   2009-06-17 15:12   디보스  80140.0  [정정]회생절차개시결정[정]  디보스  2009  
2251   2009-04-21 15:07   디보스  80140.0      회생절차개시결정[정]  디보스  2009  
2252   2009-04-07 17:55   디보스  80140.0         회생절차개시신청  디보스  2009  
27370  2010-01-26 14:34   디보스  80140.0        회생절차 폐지결정  디보스  2010  

[6 rows x 276 columns]

In [112]:
merged.loc[merged['key'] == '801402009', '공시제목']='회생절차 폐지결정'

### 평안물산 37240.0

In [79]:
merged.loc[merged['거래소코드'] == 37240.0]

회사명_x    거래소코드     회계년도 소속코드       상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약)  \
26333  평안물산(주)  37240.0  2000/12  4.0  2012/06/01     UQ  24759.0  17714.0   
26334  평안물산(주)  37240.0  2001/12  4.0  2012/06/01     UQ  48056.0  32116.0   
26335  평안물산(주)  37240.0  2002/12  4.0  2012/06/01     UQ  44564.0  27632.0   
26336  평안물산(주)  37240.0  2003/12  4.0  2012/06/01     UQ  32601.0  17553.0   
26337  평안물산(주)  37240.0  2004/12  4.0  2012/06/01     UQ  24300.0  13351.0   
26338  평안물산(주)  37240.0  2005/12  4.0  2012/06/01     UQ  17459.0  10569.0   
26339  평안물산(주)  37240.0  2006/12  4.0  2012/06/01     UQ  27098.0  16208.0   
26340  평안물산(주)  37240.0  2007/12  4.0  2012/06/01     UQ  48249.0  13399.0   
26341  평안물산(주)  37240.0  2008/12  4.0  2012/06/01     UQ  38425.0   8981.0   
26342  평안물산(주)  37240.0  2009/12  4.0  2012/06/01     UQ  21776.0   6177.0   
26343  평안물산(주)  37240.0  2010/12  4.0  2012/06/01     UQ  20419.0   7061.0   

      당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  시간  \
26333  15759.0         3316.0  ...        임시  2000  2001.0  372402001  임시   
26334  28217.0        11055.0  ...        임시  2001  2002.0  372402002  임시   
26335  24048.0         5945.0  ...        임시  2002  2003.0  372402003  임시   
26336  14699.0         3084.0  ...        임시  2003  2004.0  372402004  임시   
26337   9905.0         1712.0  ...        임시  2004  2005.0  372402005  임시   
26338   8315.0         1475.0  ...        임시  2005  2006.0  372402006  임시   
26339  15432.0        10401.0  ...        임시  2006  2007.0  372402007  임시   
26340  12769.0         1745.0  ...       0.0  2007  2008.0  372402008  임시   
26341   8524.0         1179.0  ...        임시  2008  2009.0  372402009  임시   
26342   6082.0         1967.0  ...        임시  2009  2010.0  372402010  임시   
26343   7023.0         1868.0  ...        임시  2010  2011.0  372402011  임시   

      회사명_y 종목코드                          공시제목 제출인 년_y  
26333    임시   임시                            임시  임시  임시  
26334    임시   임시                            임시  임시  임시  
26335    임시   임시                            임시  임시  임시  
26336    임시   임시                            임시  임시  임시  
26337    임시   임시                            임시  임시  임시  
26338    임시   임시                            임시  임시  임시  
26339    임시   임시                            임시  임시  임시  
26340    임시   임시                            임시  임시  임시  
26341    임시   임시                            임시  임시  임시  
26342    임시   임시                            임시  임시  임시  
26343    임시   임시  내부결산시점 관리종목 지정 또는 상장폐지 사유 발생  임시  임시  

[11 rows x 276 columns]

In [77]:
merged.loc[merged['종목코드'] == 37240.0]

회사명_x 거래소코드 회계년도 소속코드 상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약) 당좌자산(요약)  \
27371    임시    임시   임시   임시    임시     임시       임시       임시       임시   

      현금 및 현금성자산(요약)  ... EV/EBITDA 년_x 년+1        key                시간  \
27371             임시  ...        임시  임시  임시  372402012  2012-03-15 19:32   

      회사명_y     종목코드                          공시제목   제출인   년_y  
27371  평안물산  37240.0  내부결산시점 관리종목 지정 또는 상장폐지 사유 발생  평안물산  2012  

[1 rows x 276 columns]

In [78]:
merged.loc[merged['key'] == '372402011', '공시제목'] = '내부결산시점 관리종목 지정 또는 상장폐지 사유 발생'

### 에이프로테크놀로지 45470.0

In [83]:
merged.loc[merged['거래소코드'] == 45470.0]

회사명_x    거래소코드     회계년도 소속코드       상장폐지일 감사의견코드 자산총계(요약)  \
9547  (주)에이프로테크놀로지  45470.0  2000/12  4.0  2012/04/24     UQ   8491.0   
9548  (주)에이프로테크놀로지  45470.0  2001/12  4.0  2012/04/24     UQ  16676.0   
9549  (주)에이프로테크놀로지  45470.0  2002/12  4.0  2012/04/24     UQ  15814.0   
9550  (주)에이프로테크놀로지  45470.0  2003/12  4.0  2012/04/24     UQ  17830.0   
9551  (주)에이프로테크놀로지  45470.0  2004/12  4.0  2012/04/24     UQ  19749.0   
9552  (주)에이프로테크놀로지  45470.0  2005/12  4.0  2012/04/24     UQ  25537.0   
9553  (주)에이프로테크놀로지  45470.0  2006/12  4.0  2012/04/24     UQ  56938.0   
9554  (주)에이프로테크놀로지  45470.0  2007/12  4.0  2012/04/24     UQ  18484.0   
9555  (주)에이프로테크놀로지  45470.0  2008/12  4.0  2012/04/24     UQ  16201.0   
9556  (주)에이프로테크놀로지  45470.0  2009/12  4.0  2012/04/24     UQ  42009.0   
9557  (주)에이프로테크놀로지  45470.0  2010/12  4.0  2012/04/24     UQ  51411.0   

     유동자산(요약) 당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  \
9547   5988.0   5473.0          116.0  ...        임시  2000  2001.0  454702001   
9548  11116.0  10570.0          822.0  ...        임시  2001  2002.0  454702002   
9549  11017.0  10270.0          226.0  ...        임시  2002  2003.0  454702003   
9550  10329.0   9763.0          749.0  ...        임시  2003  2004.0  454702004   
9551   8032.0   7029.0          126.0  ...        임시  2004  2005.0  454702005   
9552  15367.0  14761.0          518.0  ...        임시  2005  2006.0  454702006   
9553  36080.0  36070.0           27.0  ...        임시  2006  2007.0  454702007   
9554   5836.0   5751.0           24.0  ...       0.0  2007  2008.0  454702008   
9555   3047.0   3001.0          545.0  ...        임시  2008  2009.0  454702009   
9556  19975.0  14589.0           36.0  ...     16.17  2009  2010.0  454702010   
9557  23036.0  16811.0          496.0  ...     15.08  2010  2011.0  454702011   

      시간 회사명_y 종목코드                          공시제목 제출인 년_y  
9547  임시    임시   임시                            임시  임시  임시  
9548  임시    임시   임시                            임시  임시  임시  
9549  임시    임시   임시                            임시  임시  임시  
9550  임시    임시   임시                            임시  임시  임시  
9551  임시    임시   임시                            임시  임시  임시  
9552  임시    임시   임시                            임시  임시  임시  
9553  임시    임시   임시                            임시  임시  임시  
9554  임시    임시   임시                            임시  임시  임시  
9555  임시    임시   임시                            임시  임시  임시  
9556  임시    임시   임시                            임시  임시  임시  
9557  임시    임시   임시  내부결산시점 관리종목 지정 또는 상장폐지 사유 발생  임시  임시  

[11 rows x 276 columns]

In [81]:
merged.loc[merged['종목코드'] == 45470.0]

회사명_x 거래소코드 회계년도 소속코드 상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약) 당좌자산(요약)  \
27372    임시    임시   임시   임시    임시     임시       임시       임시       임시   

      현금 및 현금성자산(요약)  ... EV/EBITDA 년_x 년+1        key                시간  \
27372             임시  ...        임시  임시  임시  454702012  2012-03-15 18:24   

           회사명_y     종목코드                          공시제목        제출인   년_y  
27372  에이프로테크놀로지  45470.0  내부결산시점 관리종목 지정 또는 상장폐지 사유 발생  에이프로테크놀로지  2012  

[1 rows x 276 columns]

In [82]:
merged.loc[merged['key'] == '454702011', '공시제목'] = '내부결산시점 관리종목 지정 또는 상장폐지 사유 발생'

### 우양에이치씨 101970.0

In [87]:
merged.loc[merged['거래소코드'] == 101970.0]

회사명_x     거래소코드     회계년도 소속코드       상장폐지일 감사의견코드  자산총계(요약)  \
24513  우양에이치씨(주)  101970.0  2003/12  4.0  2015/03/17     UQ   10168.0   
24514  우양에이치씨(주)  101970.0  2004/12  4.0  2015/03/17     UQ   24334.0   
24515  우양에이치씨(주)  101970.0  2005/12  4.0  2015/03/17     UQ   34892.0   
24516  우양에이치씨(주)  101970.0  2006/12  4.0  2015/03/17     UQ   66313.0   
24517  우양에이치씨(주)  101970.0  2007/12  4.0  2015/03/17     UQ   78402.0   
24518  우양에이치씨(주)  101970.0  2008/12  4.0  2015/03/17     UQ  131395.0   
24519  우양에이치씨(주)  101970.0  2009/12  4.0  2015/03/17     UQ  161973.0   
24520  우양에이치씨(주)  101970.0  2010/12  4.0  2015/03/17     UQ  210294.0   
24521  우양에이치씨(주)  101970.0  2011/12  4.0  2015/03/17     UQ  233181.0   
24522  우양에이치씨(주)  101970.0  2012/12  4.0  2015/03/17     UQ  316015.0   
24523  우양에이치씨(주)  101970.0  2013/12  4.0  2015/03/17     UQ  373356.0   

       유동자산(요약)  당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1  \
24513    5048.0    4268.0          453.0  ...        임시  2003  2004.0   
24514    7796.0    6731.0          772.0  ...        임시  2004  2005.0   
24515   13034.0   12722.0          177.0  ...        임시  2005  2006.0   
24516   30264.0   25145.0          143.0  ...        임시  2006  2007.0   
24517   35089.0   31054.0          443.0  ...      2.53  2007  2008.0   
24518   77255.0   69711.0         1422.0  ...      5.03  2008  2009.0   
24519  100978.0   97740.0        11569.0  ...      1.95  2009  2010.0   
24520  133253.0  125697.0         1470.0  ...      4.57  2010  2011.0   
24521  153383.0  143876.0         4510.0  ...      3.29  2011  2012.0   
24522  193413.0  182311.0         6934.0  ...      7.25  2012  2013.0   
24523  216090.0  206137.0         1693.0  ...     10.49  2013  2014.0   

              key  시간 회사명_y 종목코드  공시제목 제출인 년_y  
24513  1019702004  임시    임시   임시    임시  임시  임시  
24514  1019702005  임시    임시   임시    임시  임시  임시  
24515  1019702006  임시    임시   임시    임시  임시  임시  
24516  1019702007  임시    임시   임시    임시  임시  임시  
24517  1019702008  임시    임시   임시    임시  임시  임시  
24518  1019702009  임시    임시   임시    임시  임시  임시  
24519  1019702010  임시    임시   임시    임시  임시  임시  
24520  1019702011  임시    임시   임시    임시  임시  임시  
24521  1019702012  임시    임시   임시    임시  임시  임시  
24522  1019702013  임시    임시   임시    임시  임시  임시  
24523  1019702014  임시    임시   임시  부도발생  임시  임시  

[11 rows x 276 columns]

In [85]:
merged.loc[merged['종목코드'] == 101970.0]

회사명_x 거래소코드 회계년도 소속코드 상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약) 당좌자산(요약)  \
27373    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27374    임시    임시   임시   임시    임시     임시       임시       임시       임시   

      현금 및 현금성자산(요약)  ... EV/EBITDA 년_x 년+1         key                시간  \
27373             임시  ...        임시  임시  임시  1019702015  2015-03-04 16:49   
27374             임시  ...        임시  임시  임시  1019702015  2015-03-02 18:15   

        회사명_y      종목코드      공시제목     제출인   년_y  
27373  우양에이치씨  101970.0      부도발생  우양에이치씨  2015  
27374  우양에이치씨  101970.0  회생절차개시신청  우양에이치씨  2015  

[2 rows x 276 columns]

In [86]:
merged.loc[merged['key'] == '1019702014', '공시제목'] = '부도발생'

### 럭슬 33600.0

In [91]:
merged.loc[merged['거래소코드'] == 33600.0]

회사명_x    거래소코드     회계년도 소속코드       상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약)  \
21173  럭슬(주)  33600.0  2000/12  4.0  2021/08/11     UQ  39379.0  20589.0   
21174  럭슬(주)  33600.0  2001/12  4.0  2021/08/11     UQ  42842.0  18792.0   
21175  럭슬(주)  33600.0  2002/12  4.0  2021/08/11     UQ  50805.0  24888.0   
21176  럭슬(주)  33600.0  2003/12  4.0  2021/08/11     UQ  49951.0  20707.0   
21177  럭슬(주)  33600.0  2004/12  4.0  2021/08/11     UQ  46989.0  14891.0   
21178  럭슬(주)  33600.0  2005/12  4.0  2021/08/11     UQ  58238.0  16699.0   
21179  럭슬(주)  33600.0  2006/12  4.0  2021/08/11     UQ  56398.0  15533.0   
21180  럭슬(주)  33600.0  2007/12  4.0  2021/08/11     UQ  54904.0  18249.0   
21181  럭슬(주)  33600.0  2008/12  4.0  2021/08/11     UQ  88812.0  26849.0   
21182  럭슬(주)  33600.0  2009/12  4.0  2021/08/11     UQ  91332.0  27214.0   
21183  럭슬(주)  33600.0  2010/12  4.0  2021/08/11     UQ  89670.0  28159.0   
21184  럭슬(주)  33600.0  2011/12  4.0  2021/08/11     UQ  84482.0  16043.0   
21185  럭슬(주)  33600.0  2012/12  4.0  2021/08/11     UQ  77726.0  10945.0   
21186  럭슬(주)  33600.0  2013/12  4.0  2021/08/11     UQ  75999.0  10830.0   
21187  럭슬(주)  33600.0  2014/12  4.0  2021/08/11     UQ  70350.0  13101.0   
21188  럭슬(주)  33600.0  2015/12  4.0  2021/08/11     UQ  60597.0   8575.0   
21189  럭슬(주)  33600.0  2016/12  4.0  2021/08/11     UQ  54897.0   7657.0   
21190  럭슬(주)  33600.0  2017/12  4.0  2021/08/11     UQ  54619.0   6814.0   
21191  럭슬(주)  33600.0  2018/12  4.0  2021/08/11     UQ  66145.0  23065.0   

      당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  시간  \
21173  20383.0         4228.0  ...        임시  2000  2001.0  336002001  임시   
21174  18163.0         7707.0  ...        임시  2001  2002.0  336002002  임시   
21175  23638.0         7598.0  ...        임시  2002  2003.0  336002003  임시   
21176  18521.0         8826.0  ...        임시  2003  2004.0  336002004  임시   
21177  13739.0         5160.0  ...        임시  2004  2005.0  336002005  임시   
21178  15518.0         3626.0  ...        임시  2005  2006.0  336002006  임시   
21179  13996.0         3704.0  ...        임시  2006  2007.0  336002007  임시   
21180  17188.0         5363.0  ...      6.43  2007  2008.0  336002008  임시   
21181  25896.0         6730.0  ...      6.06  2008  2009.0  336002009  임시   
21182  25808.0         2950.0  ...     27.21  2009  2010.0  336002010  임시   
21183  27004.0         6542.0  ...     106.1  2010  2011.0  336002011  임시   
21184  14276.0         2613.0  ...     14.88  2011  2012.0  336002012  임시   
21185  10085.0         1376.0  ...    182.09  2012  2013.0  336002013  임시   
21186   9300.0           88.0  ...     146.6  2013  2014.0  336002014  임시   
21187   9689.0          742.0  ...      10.9  2014  2015.0  336002015  임시   
21188   5950.0         1691.0  ...       0.0  2015  2016.0  336002016  임시   
21189   5934.0         1414.0  ...       0.0  2016  2017.0  336002017  임시   
21190   6284.0           70.0  ...       0.0  2017  2018.0  336002018  임시   
21191  22673.0          431.0  ...       0.0  2018  2019.0  336002019  임시   

      회사명_y 종목코드          공시제목 제출인 년_y  
21173    임시   임시            임시  임시  임시  
21174    임시   임시            임시  임시  임시  
21175    임시   임시            임시  임시  임시  
21176    임시   임시            임시  임시  임시  
21177    임시   임시            임시  임시  임시  
21178    임시   임시            임시  임시  임시  
21179    임시   임시            임시  임시  임시  
21180    임시   임시            임시  임시  임시  
21181    임시   임시            임시  임시  임시  
21182    임시   임시            임시  임시  임시  
21183    임시   임시            임시  임시  임시  
21184    임시   임시            임시  임시  임시  
21185    임시   임시            임시  임시  임시  
21186    임시   임시            임시  임시  임시  
21187    임시   임시            임시  임시  임시  
21188    임시   임시            임시  임시  임시  
21189    임시   임시            임시  임시  임시  
21190    임시   임시            임시  임시  임시  
21191    임시   임시  [정정]회생절차개시신청  임시  임시  

[19 rows x 276 columns]

In [89]:
merged.loc[merged['종목코드'] == 33600.0]

회사명_x 거래소코드 회계년도 소속코드 상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약) 당좌자산(요약)  \
27375    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27376    임시    임시   임시   임시    임시     임시       임시       임시       임시   

      현금 및 현금성자산(요약)  ... EV/EBITDA 년_x 년+1        key                시간  \
27375             임시  ...        임시  임시  임시  336002020  2020-11-17 16:01   
27376             임시  ...        임시  임시  임시  336002020  2020-09-02 15:40   

      회사명_y     종목코드          공시제목 제출인   년_y  
27375    럭슬  33600.0  [정정]회생절차개시신청  럭슬  2020  
27376    럭슬  33600.0   회생절차개시신청[정]  럭슬  2020  

[2 rows x 276 columns]

In [90]:
merged.loc[merged['key'] == '336002019', '공시제목']='[정정]회생절차개시신청'

### 이노와이즈 86250.0

In [95]:
merged.loc[merged['거래소코드'] == 86250.0]

회사명_x    거래소코드     회계년도 소속코드       상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약)  \
19275  (주)화신테크  86250.0  2000/12  4.0  2021/08/31     UQ  15068.0   6276.0   
19276  (주)화신테크  86250.0  2001/12  4.0  2021/08/31     UQ  14566.0   4417.0   
19277  (주)화신테크  86250.0  2002/12  4.0  2021/08/31     UQ  13941.0   3788.0   
19278  (주)화신테크  86250.0  2003/12  4.0  2021/08/31     UQ  16421.0   4539.0   
19279  (주)화신테크  86250.0  2004/12  4.0  2021/08/31     UQ  19357.0   5994.0   
19280  (주)화신테크  86250.0  2005/12  4.0  2021/08/31     UQ  26217.0   7021.0   
19281  (주)화신테크  86250.0  2006/12  4.0  2021/08/31     UQ  34097.0  14522.0   
19282  (주)화신테크  86250.0  2007/12  4.0  2021/08/31     UQ  33153.0  12018.0   
19283  (주)화신테크  86250.0  2008/12  4.0  2021/08/31     UQ  35176.0  11011.0   
19284  (주)화신테크  86250.0  2009/12  4.0  2021/08/31     UQ  37843.0   7507.0   
19285  (주)화신테크  86250.0  2010/12  4.0  2021/08/31     UQ  51019.0   9952.0   
19286  (주)화신테크  86250.0  2011/12  4.0  2021/08/31     UQ  57129.0  13786.0   
19287  (주)화신테크  86250.0  2012/12  4.0  2021/08/31     UQ  57850.0  15754.0   
19288  (주)화신테크  86250.0  2013/12  4.0  2021/08/31     UQ  68865.0  33138.0   
19289  (주)화신테크  86250.0  2014/12  4.0  2021/08/31     UQ  76066.0  21127.0   
19290  (주)화신테크  86250.0  2015/12  4.0  2021/08/31     UQ  81877.0  27462.0   
19291  (주)화신테크  86250.0  2016/12  4.0  2021/08/31     UQ  69811.0  35543.0   
19292  (주)화신테크  86250.0  2017/12  4.0  2021/08/31     UQ  66704.0  33481.0   
19293  (주)화신테크  86250.0  2018/12  4.0  2021/08/31     UQ  55260.0  19533.0   
19294  (주)화신테크  86250.0  2020/12  4.0  2021/08/31     DU  46883.0   8511.0   

      당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  시간  \
19275   6240.0          130.0  ...        임시  2000  2001.0  862502001  임시   
19276   4412.0          126.0  ...        임시  2001  2002.0  862502002  임시   
19277   3784.0           49.0  ...        임시  2002  2003.0  862502003  임시   
19278   4536.0          325.0  ...        임시  2003  2004.0  862502004  임시   
19279   5989.0         2179.0  ...        임시  2004  2005.0  862502005  임시   
19280   7017.0          642.0  ...        임시  2005  2006.0  862502006  임시   
19281  14518.0         1276.0  ...        임시  2006  2007.0  862502007  임시   
19282  12014.0         3118.0  ...       0.0  2007  2008.0  862502008  임시   
19283  10998.0          654.0  ...      1.09  2008  2009.0  862502009  임시   
19284   7499.0         1003.0  ...     14.67  2009  2010.0  862502010  임시   
19285   9944.0         1076.0  ...     18.53  2010  2011.0  862502011  임시   
19286  13774.0          322.0  ...     18.68  2011  2012.0  862502012  임시   
19287  15737.0          751.0  ...     18.65  2012  2013.0  862502013  임시   
19288  33121.0        14496.0  ...      7.91  2013  2014.0  862502014  임시   
19289  21105.0          137.0  ...     18.01  2014  2015.0  862502015  임시   
19290  27413.0         2355.0  ...     39.19  2015  2016.0  862502016  임시   
19291  35533.0         4351.0  ...       0.0  2016  2017.0  862502017  임시   
19292  33476.0         2924.0  ...     29.71  2017  2018.0  862502018  임시   
19293  19526.0          171.0  ...       0.0  2018  2019.0  862502019  임시   
19294   8510.0         3033.0  ...       0.0  2020  2021.0  862502021  임시   

      회사명_y 종목코드      공시제목 제출인 년_y  
19275    임시   임시        임시  임시  임시  
19276    임시   임시        임시  임시  임시  
19277    임시   임시        임시  임시  임시  
19278    임시   임시        임시  임시  임시  
19279    임시   임시        임시  임시  임시  
19280    임시   임시        임시  임시  임시  
19281    임시   임시        임시  임시  임시  
19282    임시   임시        임시  임시  임시  
19283    임시   임시        임시  임시  임시  
19284    임시   임시        임시  임시  임시  
19285    임시   임시        임시  임시  임시  
19286    임시   임시        임시  임시  임시  
19287    임시   임시        임시  임시  임시  
19288    임시   임시        임시  임시  임시  
19289    임시   임시        임시  임시  임시  
19290    임시   임시        임시  임시  임시  
19291    임시   임시        임시  임시  임시  
19292    임시   임시        임시  임시  임시  
19293    임시   임시        임시  임시  임시  
19294    임시 

In [93]:
merged.loc[merged['종목코드'] == 86250.0]

회사명_x 거래소코드 회계년도 소속코드 상장폐지일 감사의견코드 자산총계(요약) 유동자산(요약) 당좌자산(요약)  \
27377    임시    임시   임시   임시    임시     임시       임시       임시       임시   
27378    임시    임시   임시   임시    임시     임시       임시       임시       임시   

      현금 및 현금성자산(요약)  ... EV/EBITDA 년_x 년+1        key                시간  \
27377             임시  ...        임시  임시  임시  862502020  2020-07-28 14:54   
27378             임시  ...        임시  임시  임시  862502020  2020-05-08 15:03   

       회사명_y     종목코드      공시제목   제출인   년_y  
27377  이노와이즈  86250.0  회생절차개시결정  화신테크  2020  
27378  이노와이즈  86250.0  회생절차개시신청  화신테크  2020  

[2 rows x 276 columns]

In [94]:
merged.loc[merged['key'] == '862502021', '공시제목'] = '회생절차개시신청'

In [125]:
#저장 
merged.to_csv('재무변수_부도사유_verSH.csv')

# 하다가말았다

In [118]:
merged.head(25)

회사명_x    거래소코드     회계년도 소속코드 상장폐지일 감사의견코드  자산총계(요약)  유동자산(요약)  \
0   (주)CMG제약  58820.0  2000/12  5.0    임시     UQ   28990.0   21169.0   
1   (주)CMG제약  58820.0  2001/12  5.0    임시     UQ   20908.0   16359.0   
2   (주)CMG제약  58820.0  2002/12  5.0    임시     UQ   15401.0    9880.0   
3   (주)CMG제약  58820.0  2003/12  5.0    임시     UQ   11063.0    8534.0   
4   (주)CMG제약  58820.0  2004/12  5.0    임시     UQ    5179.0    3893.0   
5   (주)CMG제약  58820.0  2005/12  5.0    임시     UQ    8280.0    3449.0   
6   (주)CMG제약  58820.0  2006/12  5.0    임시     UQ   10030.0    6897.0   
7   (주)CMG제약  58820.0  2007/12  5.0    임시     UQ   22074.0    8952.0   
8   (주)CMG제약  58820.0  2008/12  5.0    임시     UQ   34557.0   16725.0   
9   (주)CMG제약  58820.0  2009/12  5.0    임시     UQ   22836.0    9827.0   
10  (주)CMG제약  58820.0  2010/12  5.0    임시     UQ   24128.0   11604.0   
11  (주)CMG제약  58820.0  2011/12  5.0    임시     UQ   27549.0   15265.0   
12  (주)CMG제약  58820.0  2012/12  5.0    임시     UQ   56989.0   47073.0   
13  (주)CMG제약  58820.0  2013/12  5.0    임시     UQ   55962.0   38259.0   
14  (주)CMG제약  58820.0  2014/12  5.0    임시     UQ   58127.0   28360.0   
15  (주)CMG제약  58820.0  2015/12  5.0    임시     UQ   56592.0   26331.0   
16  (주)CMG제약  58820.0  2016/12  5.0    임시     UQ  110980.0   78772.0   
17  (주)CMG제약  58820.0  2017/12  5.0    임시     UQ  109568.0   81227.0   
18  (주)CMG제약  58820.0  2018/12  5.0    임시     UQ  114380.0   81370.0   
19  (주)CMG제약  58820.0  2019/12  5.0    임시     UQ  192243.0  150584.0   
20  (주)CMG제약  58820.0  2020/12  5.0    임시     UQ  195356.0  145981.0   
21   (주)ES큐브  50120.0  2001/06  5.0    임시     UQ    7040.0    3825.0   
22   (주)ES큐브  50120.0  2002/06  5.0    임시     UQ    9447.0    5384.0   
23   (주)ES큐브  50120.0  2003/06  5.0    임시     UQ    9538.0    5792.0   
24   (주)ES큐브  50120.0  2004/06  5.0    임시     UQ   15645.0   11859.0   

    당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1        key  시간 회사명_y  \
0    10541.0         4330.0  ...        임시  2000  2001.0  588202001  임시    임시   
1     2307.0         1829.0  ...        임시  2001  2002.0  588202002  임시    임시   
2     1436.0          355.0  ...        임시  2002  2003.0  588202003  임시    임시   
3     1083.0            2.0  ...        임시  2003  2004.0  588202004  임시    임시   
4      445.0           11.0  ...        임시  2004  2005.0  588202005  임시    임시   
5     3226.0          609.0  ...        임시  2005  2006.0  588202006  임시    임시   
6     6897.0         2850.0  ...        임시  2006  2007.0  588202007  임시    임시   
7     8638.0         2714.0  ...       0.0  2007  2008.0  588202008  임시    임시   
8    15015.0         6233.0  ...        임시  2008  2009.0  588202009  임시    임시   
9     7398.0         1063.0  ...        임시  2009  2010.0  588202010  임시    임시   
10    8721.0         2447.0  ...        임시  2010  2011.0  588202011  임시    임시   
11   12522.0         1152.0  ...     18.52  2011  2012.0  588202012  임시    임시   
12   44118.0         4673.0  ...       0.0  2012  2013.0  588202013  임시    임시   
13   33640.0        21705.0  ...     31.32  2013  2014.0  588202014  임시    임시   
14   23447.0         8827.0  ...     37.53  2014  2015.0  588202015  임시    임시   
15   20875.0         2566.0  ...       0.0  2015  2016.0  588202016  임시    임시   
16   72378.0         2149.0  ...     89.66  2016  2017.0  588202017  임시    임시   
17   73323.0         3799.0  ...    197.94  2017  2018.0  588202018  임시    임시   
18   72798.0        13464.0  ...    101.42  2018  2019.0  588202019  임시    임시   
19  141535.0        18571.0  ...    121.46  2019  2020.0  588202020  임시    임시   
20  130934.0         8044.0  ...    186.77  2020  2021.0  588202021  임시    임시   
21    3713.0          509.0  ...        임시  2001  2002.0  501202002  임시    임시   
22    5279.0         1671.0  ...        임시  2002  2003.0  501202003  임시    임시   
23    5725.0          256.0  ...        임시  2003  2004.0  501202004  임시    임시   
24   11767.0         3992.0  ...        임시  2004  2005.0  501202005  임시    임시   

   종목코드 공시제목 제출인 년_y  
0   

In [124]:
merged[merged['상장폐지일']!='임시']

회사명_x    거래소코드     회계년도 소속코드       상장폐지일 감사의견코드  자산총계(요약)  \
89          (주)강원랜드  35250.0  2000/12  4.0  2003/09/04     UQ  342867.0   
90          (주)강원랜드  35250.0  2001/12  4.0  2003/09/04     UQ  695214.0   
91          (주)강원랜드  35250.0  2002/12  4.0  2003/09/04     UQ  823397.0   
109    (주)경윤하이드로에너지  19120.0  2000/12  4.0  2011/04/06     UQ   26486.0   
110    (주)경윤하이드로에너지  19120.0  2001/12  4.0  2011/04/06     UQ   29152.0   
...             ...      ...      ...  ...         ...    ...       ...   
27296      후야인포넷(주)  32050.0  2000/12  4.0  2005/04/26     UQ   85700.0   
27297      후야인포넷(주)  32050.0  2001/12  4.0  2005/04/26     UQ   46044.0   
27298      후야인포넷(주)  32050.0  2002/12  4.0  2005/04/26     UQ   47519.0   
27299      후야인포넷(주)  32050.0  2003/12  4.0  2005/04/26     UQ    7221.0   
27300      후야인포넷(주)  32050.0  2004/12  4.0  2005/04/26     UQ    2838.0   

       유동자산(요약)  당좌자산(요약) 현금 및 현금성자산(요약)  ... EV/EBITDA   년_x     년+1  \
89     237186.0  236754.0        18590.0  ...        임시  2000  2001.0   
90     475862.0  475317.0        21465.0  ...        임시  2001  2002.0   
91     363480.0  362979.0        42581.0  ...        임시  2002  2003.0   
109     18402.0   13295.0          690.0  ...        임시  2000  2001.0   
110     20959.0   13498.0          341.0  ...        임시  2001  2002.0   
...         ...       ...            ...  ...       ...   ...     ...   
27296   65529.0   33237.0        15397.0  ...        임시  2000  2001.0   
27297   30164.0   22085.0        11444.0  ...        임시  2001  2002.0   
27298   36339.0   28204.0         4355.0  ...        임시  2002  2003.0   
27299    4570.0    3687.0          844.0  ...        임시  2003  2004.0   
27300    1445.0    1445.0          532.0  ...        임시  2004  2005.0   

             key  시간 회사명_y 종목코드 공시제목 제출인 년_y  
89     352502001  임시    임시   임시   임시  임시  임시  
90     352502002  임시    임시   임시   임시  임시  임시  
91     352502003  임시    임시   임시   임시  임시  임시  
109    191202001  임시    임시   임시   임시  임시  임시  
110    191202002  임시    임시   임시   임시  임시  임시  
...          ...  ..   ...  ...  ...  ..  ..  
27296  320502001  임시    임시   임시   임시  임시  임시  
27297  320502002  임시    임시   임시   임시  임시  임시  
27298  320502003  임시    임시   임시   임시  임시  임시  
27299  320502004  임시    임시   임시   임시  임시  임시  
27300  320502005  임시    임시   임시   임시  임시  임시  

[5436 rows x 276 columns]

In [ ]:
train_full